### PR TITLE
Removes Doc_status links from the MDNSidebar macro

### LINKED ISSUE #1800: Doc_status links must be removed
Doc_status is no more once we land Yari.
Screen Shot 2020-11-20 at 7 01 52 PM
I suspect it just needs to be removed from the MDNSidebar macro.

### PR DESCRIPTION
**Pull request by tannerdolby**
Fixes #1800

### CODE REVIEW

**Review by peterbe — CHANGES_REQUESTED** [review]
You can also remove where it's *defining* the `Doc_status_by_topic`.

**Comment by tannerdolby** [comment]
@peterbe I wiped `Doc_status` and `Doc_status_by_topic` off the face of the earth. There is still a few spots within the project where `Doc_status` exists, but I wanted to ask you about it first before removing.

1. `import/constants.js:36:  "MDN/Doc_status"`
2. Within the `href` for many list item links in `kumascript/macros/DocStatusQuickLinks.ejs`
```
<li><strong><a href="/<%=env.locale%>/docs/MDN/Doc_status"><%=titleValues['Doc_status']%></a></strong></li>
```
```
<li><a href="/<%=env.locale%>/docs/MDN/Doc_status/API"><%=titleValues['API']%></a></li>
```

Let me know if I should leave this stuff alone or remove as well.

**Comment by peterbe** [comment]
@escattone There are only 3 places where `DocStatusQuickLinks.ejs` is used. 
* files/en-us/web/guide/index/index.html
* files/ko/web/guide/index/index.html
* files/ja/web/guide/index/index.html

In exactly 1 week, these are all going to be useless. Since in all of those pages, it doesn't actually render anything (because they all have a different sidebar that wins). So I removed it from all those pages. 

Are you OK with @tannerdolby simply deleting that `.ejs` file now?

**Comment by peterbe** [comment]
>     1. import/constants.js:36:  "MDN/Doc_status"

This is still needed but in about 1 week, it will never be needed again because that day that whole file will be deleted.

**Review by peterbe — APPROVED** [review]
Waiting to hear confirmation from @escattone regarding the deletion of that other .ejs files.

**Comment by escattone** [comment]
@peterbe @tannerdolby 

> Are you OK with @tannerdolby simply deleting that .ejs file now?

Yes, blast away! :)

**Comment by tannerdolby** [comment]
@escattone Ok great! :) I will proceed with deleting the `DocStatusQuickLinks.ejs` file.

**Review by peterbe — APPROVED** [review]
Ahhh. I feel lighter already.

**Comment by peterbe** [comment]
Perhaps this one you can take a look at next: https://github.com/mdn/yari/issues/1722

**Pull request merged**
