### PR TITLE
Add and update Japanese translations in scripts

### PR DESCRIPTION
**Pull request by mfuji09**
- CSSSyntax.ejs, CompatUnknown.ejs, optionalGeneric.ejs: added some Japanese translations
- DeprecatedGeneric.ejs: update an outdated translation
- SeeCompatibleTable.ejs: update a translation for consistency
- PreviousNext.ejs, nextPage.ejs, previousPage.ejs: update translations for consistency
- spec2.ejs: update incorrect translations

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
These changes look fine to me, but one of the tests appears to be failing because the MDN Kitchensink page is no longer in the content. I know this because I deleted it last night (it contains lots of really out of date stuff that doesn't work any more).

I really don't get why any of the tests for these macros would rely on the MDN kitchen sink page. This is just really bizarre. @escattone / @peterbe , and you help me shed some light on this?

**Comment by peterbe** [comment]
Blocked on https://github.com/mdn/content/pull/1001

**Comment by peterbe** [comment]
@chrisdavidmills Tests are passing now. Wanna merge?

**Comment by mfuji09** [comment]
Thank you all!

**Pull request merged**
