### PR TITLE
chore(macros): delete NoteStart and NoteEnd

### PR DESCRIPTION
**Pull request by MrBrain295**
## Summary
Delete the notestart and noteend macros.

### Problem
It’s not needed.

### Solution
Delete it.

---

### After

---

### CODE REVIEW

**Review by caugner — CHANGES_REQUESTED** [review]
Those are used by the `Note` macro. Is that one no longer used anywhere?

https://github.com/mdn/yari/blob/afbb4b22ff18e4cf2526e5550e9671d0314f1a64/kumascript/macros/Note.ejs#L8

**Comment by MrBrain295** [comment]
There are a few occurrences in Russian and a or to remove them.

**Comment by nschonni** [comment]
@caugner last upstream instances in translated-content are removed now

**Review by caugner — APPROVED** [review]
Verified that all three macros are no longer used in content/translated-content.

**Pull request merged**
