### PR TITLE
fix(nav): use <aside> and un-nested <nav>s for better semantics

### PR DESCRIPTION
**Pull request by danngo342**
## Summary

Fixes https://github.com/mdn/yari/issues/6852.

- Chore for https://github.com/mdn/yari/issues/6852
- I think I followed the guidelines for making this PR, but if I did anything wrong, then I'll try to correct it right away (as this is my first ever PR to any open source project).

### Problem
- The problem deals with semantics, rather than functionality. In [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside#examples), there is a table of contents component that contains navigation links as children. The parent of such components should be a `nav` by convention, but is currently an `aside` tag instead.

### Solution
- I followed the suggestion as suggested by caugner: https://github.com/mdn/yari/issues/6852#issuecomment-1219815019
- The suggestion ensures that the nav tag doesn't become nested, while fulfills the responsive design requirements of the TOC
- The issue didn't explicitly specify, but I believe that there should be no visual changes to rendered ui page

## How did you test this change?
- I followed the requirements specified by https://github.com/mdn/yari/issues/6852#issuecomment-1219815019
- Specifically, I opened a debugger on the page in question to make sure that the html tags are changed suggested, and that the components are correctly laid out/located responsively

### CODE REVIEW

**Comment by caugner** [comment]
Besides, welcome and congratulations on your first PR to an open source project, @danngo342! 🎉 🎉 🎉

**Comment by danngo342** [comment]
> LGTM, thank you! 🎉
> 
> @danngo342 I feel like we could also make `div#sidebar-quicklinks` and `div.toc` both `<aside>` elements, while we're at it. What do you think?

Yes, I'll try that out. Now disclaimer, I'm quite inexperienced outside of my day-job with React. However, from what I understand, yes, both of those `divs` seem to fulfill the roles better as `asides`, rather than purely being stylistic containers, as `divs` imply

Since you approved the PR, would you rather that I make a separate PR for the aforementioned `divs`, or just commit onto this PR? I'm fine with either approach, but I just want to make sure that I do things that's less stressful for reviewers/maintainers

**Comment by caugner** [comment]
Sorry about the delay, I was out of office for a week.

> Now disclaimer, I'm quite inexperienced outside of my day-job with React.

No worries about that, I'm here to assist.



> Since you approved the PR, would you rather that I make a separate PR for the aforementioned `divs`, or just commit onto this PR?

Yes, you can directly commit to this PR/branch. Once you pushed your commit, you can re-request a review on the right:
image

**Comment by danngo342** [comment]
Gotcha, thank you for letting me know. By coincidence, I've also been pre-occupied for the past week and a half. Sorry about that; next time I'll send notice, just so I develop a good habit for when I contribute more in the future

On that note, I'll make sure to start implementing the feedback you requested this week

**Review by caugner — APPROVED** [review]

**Comment by danngo342** [comment]
Thank you, and sorry for not finishing this up earlier. I'll try to be better, next time

**Comment by caugner** [comment]
> Thank you, and sorry for not finishing this up earlier. I'll try to be better with this, next time

Don't worry about it at all. If you look at the list of open PRs, we have quite some unfinished PRs that are much older than yours. It's really not a problem. 😉

**Pull request merged**
