### PR TITLE
feat(surveys): add Interop 2023 survey

### PR DESCRIPTION
**Pull request by caugner**
### Solution

---

### After

---

### CODE REVIEW

**Comment by schalkneethling** [comment]
We do not yet have official sign off but I reckon we can merge this one.
https://github.com/mdn/short-surveys/discussions/1#discussioncomment-3992950

@caugner @Guyzeroth @fiji-flo @Rumyra

**Comment by schalkneethling** [comment]
> We do not yet have official sign off but I reckon we can merge this one. [mdn/short-surveys#1 (reply in thread)](https://github.com/mdn/short-surveys/discussions/1#discussioncomment-3992950)
> 
> @caugner @Guyzeroth @fiji-flo @Rumyra

We do have sign off to go live. Thanks, everyone.

**Comment by foolip** [comment]
Thanks everyone for making this happen on a Friday. I'm very grateful.

**Comment by foolip** [comment]
@caugner @schalkneethling can this go out now?

**Review by fiji-flo — APPROVED** [review]

**Pull request merged**
