### PR TITLE
Fix case of compatibility table anchor

### PR DESCRIPTION
**Pull request by todduk**
Fixes an issue I reported on the [content repo](https://github.com/mdn/content/issues/1585) where the link to the compatibility table in the deprecation warning box was not working due to a mismatch in letter casing.

I'm not able to build and test, sorry.

### CODE REVIEW

**Comment by mattiapontonio** [comment]
How about use `browser-compatibilty`?

**Comment by todduk** [comment]
@mattiapontonio sorry, I'm not sure if you're saying my fix is out of scope or your additional suggestions are.
I didn't realise I hadn't applied a GPG key to my account here. I can close and re-submit a signed commit

**Comment by mattiapontonio** [comment]
@todduk mine are. 
Sometimes i comment around Just to open issues.
The PR seems ok since the CI passes.
I can't merge since I'm not official.
👍

Tip
Of You use GitHub web commits are signed.

**Comment by todduk** [comment]
Closing to resubmit signed commit

**Pull request closed without merging**
