### PR TITLE
Add Deno to browser compat data table

### PR DESCRIPTION
**Pull request by lucacasonato**
This commit adds Deno BCD to the browser compat data table. The "servers"
category (Deno and Node.js) is shown if either Node.js or Deno has compat data
for a given API.

TODOs:

- [x] Switch to new release of @mdn/dinocons once that is release. Will
  include this PR: https://github.com/mdn/mdn-dinocons/pull/37
- [x] Switch to 4.0.0 release of BCD once that is released. This will include
  data for Deno.

### CODE REVIEW

**Comment by schalkneethling** [comment]
In terms of the SVG, does this work @lucacasonato?

Screenshot 2021-08-10 at 19 14 54

**Comment by lucacasonato** [comment]
@schalkneethling Yeah, that is what I used now. All the other logos are pure black/transparent and less detailed though (the Deno one is very slightly gray if I remember right). Maybe best would just be if I make the image fully black and white. I'll play around with it and see if I can make it look like the other icons.
image

**Comment by lucacasonato** [comment]
@schalkneethling I have opened a PR to add a black icon for Deno to @mdn/dinocons: mdn/mdn-dinocons#37. Figma asset is included too.

This PR now links to my GH fork of @mdn/dinocons. This will need to be resolved before the PR can be landed.

**Comment by schalkneethling** [comment]
> @schalkneethling I have opened a PR to add a black icon for Deno to @mdn/dinocons: [mdn/mdn-dinocons#37](https://github.com/mdn/mdn-dinocons/pull/37). Figma asset is included too.
> 
> This PR now links to my GH fork of @mdn/dinocons. This will need to be resolved before the PR can be landed.

Thank you, this has been merged. I will do a release either today or tomorrow.

**Comment by lucacasonato** [comment]
Thanks @schalkneethling!

**Comment by schalkneethling** [comment]
> Thanks @schalkneethling!

Release incoming https://github.com/mdn/mdn-dinocons/pull/40

**Comment by ddbeck** [comment]
[BCD v4.0.0 just dropped](https://github.com/mdn/browser-compat-data/releases/tag/v4.0.0), which is the first BCD release to contain Deno data. Looking forward to seeing this PR ship after Yari upgrades!

**Comment by lucacasonato** [comment]
Todos have been resolved, PR now ready for review :-)

**Review by peterbe — APPROVED** [review]
Code changes look great. Great if someone else could test and check it too.

**Review by schalkneethling — APPROVED** [review]
r+ Thanks so much @lucacasonato 🦖

**Pull request merged**
