### PR TITLE
dynamic favicon based on flaws count

### PR DESCRIPTION
**Pull request by peterbe**
Check out the cool favicons that change depending on the flaw count. 
Screen Shot 2021-05-12 at 11 16 45 PM

Whimsical? Maybe. Cute? Maybe. Landable? Maybe. Fun Friday hack? Definitely!

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
Woot, no SVG Facicons?
https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/

**Comment by schalkneethling** [comment]
> Woot, no SVG Facicons?
> https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/

It’s coming :)

**Review by schalkneethling — APPROVED** [review]
Neato! r+

**Comment by peterbe** [comment]
> Neato! r+

Did you want to update the favicon image files or can we merge it?

**Comment by schalkneethling** [comment]
> > Neato! r+
> 
> Did you want to update the favicon image files or can we merge it?

Nope, go for it.

**Pull request merged**
