### PR TITLE
fix(kumascript): add translations() to page info

### PR DESCRIPTION
**Pull request by yin1999**
## Summary

Part of: #7438

### Problem

See the above issue.

### Solution

use `translationsOf` to get cached translations.

---

## Screenshots

| url | Used macro | Before | After |
| --- | --- | ----------------- | ------------------- |
| /zh-CN/docs/Web/API/Fetch_API/Basic_concepts | DefaultAPISidebar | image | image |
| /zh-CN/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets | ListSubpagesForSidebar | image | image |
| /zh-CN/docs/Web/CSS/CSS_animations | CSSRef | image | image |
| /zh-CN/docs/Web/JavaScript/Reference/Global_Objects/AggregateError/AggregateError | JSRef | image | image |

---

## How did you test this change?

run `yarn dev` and check rendered images.

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@yin1999 apart from the maintenance load required for conflicts, is there another reason for closing this?

**Comment by yin1999** [comment]
Hey @SphinxKnight. I found that the current modification will make some macros (which have `translations()` method used) tests take a long time, and this would cause the tests to fail. Unfortunately, I don't have bandwidth to fix this issue for now :(

**Comment by SphinxKnight** [comment]
> Hey @SphinxKnight. I found that the current modification will make some macros (which have `translations()` method used) tests take a long time, and this would cause the tests to fail. Unfortunately, I don't have bandwidth to fix this issue for now :(

thanks a lot already :) I'll see what I can do :)

**Comment by yin1999** [comment]
> > Hey @SphinxKnight. I found that the current modification will make some macros (which have `translations()` method used) tests take a long time, and this would cause the tests to fail. Unfortunately, I don't have bandwidth to fix this issue for now :(
> 
> thanks a lot already :) I'll see what I can do :)

I've fixed the tests. Feel free to share any ideas /;

**Review by caugner — APPROVED** [review]
LGTU (@argl @fiji-flo @caugner), thanks! 🎉

**Pull request merged**
