### PR TITLE
chore(macros/Firefox_for_developers): remove the parameter and add zh-CN translation

### PR DESCRIPTION
**Pull request by yin1999**
## Summary

1. Added zh-CN translation for this macro.
2. Removed the usage of "version" param, as this is not really necessary (we can infer the version information from the `slug`).

### Solution

Gather the version info from the `slug`.

---

## Screenshots

| URL | Before | After |
| --- | --- | --- |
| /en-US/docs/Mozilla/Firefox/Releases/2 | image | image |
| /en-US/docs/Mozilla/Firefox/Releases/3.6 | image | image |
| /en-US/docs/Mozilla/Firefox/Releases/4 | image | image |
| /en-US/docs/Mozilla/Firefox/Releases/24 | image | image |
| /en-US/docs/Mozilla/Firefox/Releases/121 | image | image |

Note, the lists in `/en-US/docs/Mozilla/Firefox/Releases/2` are not consistent.

---

## How did you test this change?

1. Run `yarn dev` and check rendered page
2. Run `rg -il "Firefox_for_developers"` to check the occurrences of this macro in content and translated-content.

### CODE REVIEW

**Review by jasonren0403 — APPROVED** [review]
LGTM for zh-CN translation 👍

**Comment by yin1999** [comment]
ping @bsmth for another eye on this PR :)

**Review by bsmth — APPROVED** [review]
Looks way more readable to me, thank you! Leaving it for other expert eyes to take a look before merging 👀 

__edit 30th Nov:__ I'll ask engineering about this one today, thanks for the patience 🙏🏻

**Comment by bsmth** [comment]
(Quick update) - The engineering team know about this one and will get around to it soon, hopefully. 🙏🏻

**Review by fiji-flo — APPROVED** [review]
Sorry for the long delay and thanks a for cleaning this up.

**Comment by yin1999** [comment]
Thanks for the review @fiji-flo. Is there any thing blocking this?

**Comment by fiji-flo** [comment]
@yin1999 just didn't press the button

**Comment by hamishwillee** [comment]
FWIW I am not sure why we show the "older versions" rather than "all versions". On release of a new version there is no difference. Later on when version "x" is old, I am unlikely to care about version x-1, but I might well care about the current version.

**Pull request merged**
