### PR TITLE
Add Ctrl/Cmd+K as a Keyboard Shortcut for search

### LINKED ISSUE #5935: Search keyboard shortcut
### MDN URL

all

### What specific section or headline is this issue about?

Search keyboard shortcut

### What information was incorrect, unhelpful, or incomplete?

There are no keyboard shortcut to invoke search, have to manually go click on that small area at the top to search.

### What did you expect to see?

Something like <kbd>alt</kbd><kbd>shift</kbd><kbd>f</kbd> like those in media wiki pages or <kbd>s</kbd> or <kbd>/</kbd> like those in other documentation, when press it allows user to type in the text to start searching.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by danielhjacobs**
## Summary

Fixes #5935

### Problem

Vimium overrides / by default.

### Solution

Add another keyboard shortcut for search

## How did you test this change?

Locally on Firefox, tried Ctrl+k and Ctrl+K (capital and lowercase). Locally on Chrome, tried ⊞ + k (which is the metaKey for Chromium browsers on Windows, like Cmd is for browsers on Mac: see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey)

### CODE REVIEW

**Comment by pickfire** [comment]
Why is it meta+k? I have never seen similar search doing this. Also, this conflicts with the some browsers search function, like ctrl-k is used to invoke search engine in firefox.

**Comment by danielhjacobs** [comment]
> Why is it meta+k?

Ask @caugner, as I'm just following his suggestion: https://github.com/mdn/yari/issues/5935#issuecomment-1096556296

**Comment by caugner** [comment]
> Why is it meta+k? I have never seen similar search doing this. Also, this conflicts with the some browsers search function, like ctrl-k is used to invoke search engine in firefox.

Unless I'm mistaken, this is rather common. For example, https://vuejs.org/ suggests <kbd>⌘</kbd> + <kbd>K</kbd> on Mac OS.

See: https://docsearch.algolia.com/

> We aim at keeping the experience as smooth as your interaction with an IDE, which explains the Ctrl+K (⌘+K on macOS) keyboard shortcut to open the search modal.

**Comment by danielhjacobs** [comment]
Also, I notice ctrl+k works on this very website (Github)

**Review by caugner — CHANGES_REQUESTED** [review]

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
Thanks a lot, @danielhjacobs! 🎉

**Pull request merged**
