### PR TITLE
fix(macros): improve the translation of secureContextGeneric for zh-CN

### PR DESCRIPTION
**Pull request by yin1999**
## Summary

Follow #3883:

- update the anchor (in zh-CN) to `Browser compatibility` ("浏览器兼容性" in zh-CN)

And also improve the translation of this sentence.

### Before

image

### After

image

### CODE REVIEW

**Comment by yin1999** [comment]
pin @irvin for a review :)

**Comment by irvin** [comment]
lgfm

**Comment by yin1999** [comment]
> lgfm

It's time to pin @mdn/core-yari-dev.

**Review by schalkneethling — APPROVED** [review]
Thank you, @yin1999 🎉

**Pull request merged**
