### PR TITLE
fix nested dl's with p

### PR DESCRIPTION
**Pull request by fiji-flo**
<dl>
  <dt>thing</dt>
  <dd>nested definition:
    <dl>
      <dt>thang</dt>
      <dd>stuff</dd>
    </dl>
    <p>I'm what breaks it</p>
  </dd>
</dl>

was broken

### CODE REVIEW

**Comment by fiji-flo** [comment]
resolves #4205

**Comment by fiji-flo** [comment]
We could spend more work to not insert additional paragraphs but that's tedious work. This is a rough explanation of `spread` https://github.com/remarkjs/remark/pull/364

@wbamberg I don't think it's worth it, how about you?

**Comment by wbamberg** [comment]
To be clear, is the PR in https://github.com/mdn/content/pull/6936 generated using this patched version?

If so it looks fine to me.

**Comment by fiji-flo** [comment]
Yes https://github.com/mdn/content/pull/6936 was generated with this PR

**Comment by peterbe** [comment]
How should I review this? Because of the way we split up the work, I never worked on the Markdown AST stuff so I have not frame of reference to understand it. 
Wouldn't it be better if @wbamberg reviews this. He stands a much better chance at understanding if the code change solves the problem. 
I could review it but it'd be quite an investment to first understand what it does and how it works.

**Comment by fiji-flo** [comment]
I cannot add @wbamberg as a reviewer but he gave his okay. Happy to just merge it.

**Pull request merged**
