### PR TITLE
fix: links in bcd tables

### LINKED ISSUE #1887: Impossible to see what's a link and what isn't in BCD table
E.g. http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json
Screen Shot 2020-11-30 at 8 59 54 AM

You can't see which elements are clickable. 
You can find out if you hover the mouse over each and every one since then they light up the background:
Screen Shot 2020-11-30 at 9 00 39 AM

### PR DESCRIPTION
**Pull request by schalkneethling**
Make it easy to identify links in the BCD tables

### Initial

Screenshot 2020-12-01 at 17 35 07

### Hover

Screenshot 2020-12-01 at 17 39 35

fix #1887Make it easy to identify links in the BCD tables

fix #1887

### CODE REVIEW

**Review by peterbe — CHANGES_REQUESTED** [review]
It's better but why are the `<a><code>` tags in the BCD table allowed to be blue and easily identifiable as links but not the `<a><code>` that appear elsewhere in the document?

And why introduce a new shade of blue? Now there are 3 different colors for links.

Screen Shot 2020-12-01 at 3 02 37 PM


Can't we just do what Kuma does? I can't believe I'm saying this but it was perfect there. 
Screen Shot 2020-12-01 at 3 05 25 PM

**Comment by schalkneethling** [comment]
> It's better but why are the `<a><code>` tags in the BCD table allowed to be blue and easily identifiable as links but not the `<a><code>` that appear elsewhere in the document?
> 
> And why introduce a new shade of blue? Now there are 3 different colors for links.

This issue is specifically about the problem in BCD tables. While I did this, I looked at the color contrast of the current link color, and while it is fine on a white background, on these backgrounds it is not, and this color works much better.

After having done some more looking into links in other places, I have decided to switch all links to `$primary-blue-50` as it gives us better color contrast overall. That change happens in minimalist though.

**Comment by peterbe** [comment]
I don't know how to review this. 
I still see 3 different styles for these links. 
Screen Shot 2020-12-02 at 8 21 25 AM

**Comment by peterbe** [comment]
If this requires an orchastrated change in minimalist at the same time, perhaps you can take some screenshots to demonstrate how to test it in Storybook or something.

**Comment by schalkneethling** [comment]
> If this requires an orchastrated change in minimalist at the same time, perhaps you can take some screenshots to demonstrate how to test it in Storybook or something.

Let me make the change in minimalist and get that into this branch.

**Comment by schalkneethling** [comment]
Screenshot 2020-12-02 at 18 31 34

Screenshot 2020-12-02 at 18 31 52

**Review by peterbe — APPROVED** [review]
Is it consistent throughout now?

**Comment by schalkneethling** [comment]
> Is it consistent throughout now?

Indeed it is 🎉

**Pull request merged**
