### PR TITLE
mathml polyfill

### LINKED ISSUE #4197: Some pages show raw math syntax (LaTeX?)
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PeriodicWave

#### What information was incorrect, unhelpful, or incomplete?

"\left(a+bi\right)e^{i} , \left(c+di\right)e^{2i} , \left(f+gi\right)e^{3i}" appears on this page, which is unreadable. It looks a bit like LaTeX, presumably this was once turned into a math image?

#### Specific section or headline?

* https://developer.mozilla.org/en-US/docs/Web/API/PeriodicWave#example
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/PI
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

#### What did you expect to see?

No expectations, just not this :)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/periodicwave`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PeriodicWave
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/periodicwave/index.html
* Last commit: https://github.com/mdn/content/commit/babc0473793bbe3cfa66cd96fae7f84348be373b
* Document last modified: 2021-02-08T10:05:46.000Z

</details>

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #4197

In theory, it works :)
But it doesn't look great. That's why it's a Draft. 

What I did was that the Yari builder looks through the document's rendered HTML and looks for any `<math>` tag. 
If there is one, the `index.json` get's an `hasMathML=true`. Now, if that's present, in the `<Document/>` component, it loads `<MathMLPolyfillMaybe/>` lazily. That component has the code from https://github.com/mdn/kuma/pull/6546/files (rewritten in TypeScript) which essentially executes the `isMathMLSupported` function there. 
If it finds that `isMathMLSupported() === false` it then lazy-loads another component called `<MathMLPolyfill/>` which in term makes sure the `mathml.css` from https://github.com/fred-wang/mathml.css/blob/master/mathml.css gets injected into the DOM. 

But it doesn't look great in Chrome :( 
And I don't know why. 

Screen Shot 2021-07-15 at 2 52 27 PM

Screen Shot 2021-07-15 at 2 53 17 PM

It looks marginally better in Chrome compare to the current Prod which looks like this:
Screen Shot 2021-07-15 at 2 57 41 PM

So can someone look into the use of that CSS. Is there perhaps something we're doing incorrectly. Perhaps we have existing CSS that negatively affects the CSS with some sorts of conflicts.

### CODE REVIEW

**Comment by peterbe** [comment]
I pasted in some more complex examples from view-source:http://fred-wang.github.io/mathml.css/
and it looks like this in Chrome:
Screen Shot 2021-07-15 at 3 00 49 PM

**Comment by peterbe** [comment]
Try opening http://fred-wang.github.io/mathml.css/ in Chrome and compare. 
Clearly our CSS has more padding and perhaps that's why. The font-family is different too.

**Comment by peterbe** [comment]
@schalkneethling Can you spin up this PR in your Chrome and see if there's something we can do to "unset" some CSS or mess with some padding in our SCSS.

**Comment by schalkneethling** [comment]
> @schalkneethling Can you spin up this PR in your Chrome and see if there's something we can do to "unset" some CSS or mess with some padding in our SCSS.

Will do.

**Comment by schalkneethling** [comment]
I had a look over this and added the `STIX` font for better MathML rendering.
This is without the polyfill:

Screenshot showing broken MathML rendering

This is with the polyfill and STIX:

Screenshot showing the improved MathML rendering

Tested in both Chrome and Edge

**Comment by Rumyra** [comment]
Ooof this looks nice @schalkneethling 👍

**Review by Rumyra — APPROVED** [review]

**Pull request merged**
