### PR TITLE
chore: Add EditorConfig for whitespace

### PR DESCRIPTION
**Pull request by nschonni**
Copied from original version in mdn/content and added Python config

### CODE REVIEW

**Comment by peterbe** [comment]
How do I test this? Like, is there a command line thing I can run that compares the config with a file?

**Review by peterbe — APPROVED** [review]
Makes sense. I'm still not 100% comfortable with EditorConfig. I'm so confused as to what's going with VSCode and Black and Prettier and the magic is mixes. 

Any objections @fiji-flo ?

**Comment by nschonni** [comment]
> How do I test this? Like, is there a command line thing I can run that compares the config with a file?

No, it's really aimed at telling your IDE what it should use. There is an old depricated tool someone else wrote called "eclint". Might do a separate PR with some cleanups with it later, but it's 'dumb' and doesn't do any proper AST. Tools like Prettier also read this config

**Comment by Ryuno-Ki** [comment]
> How do I test this?

Ideally, your IDE should insert the right indentation (or even fix it?) depending on what's defined.
As mentioned before, there's a VS Code extension that teaches VS Code how to read an .editorconfig.

**Comment by peterbe** [comment]
@fiji-flo ping r?

**Review by fiji-flo — APPROVED** [review]
👍 guess I'll delete my local `.editorconfig` now

**Pull request merged**
