### PR TITLE
Bump BCD to v5.1.0

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates the names of the types from BCD and updates BCD v5.1.0.  (Note: going forward, TypeScript definitions will be covered by semantic versioning.)

### CODE REVIEW

**Comment by schalkneethling** [comment]
@queengooborg Should we prefer this one over https://github.com/mdn/yari/pull/6494 i.e. merge this and just ignore the dependabot one? I know yours does have additional changes over what the dependabot one does.

**Comment by queengooborg** [comment]
Yes, #6494 should be closed in favor of this PR because there were some TypeScript changes in the most recent release!

**Comment by queengooborg** [comment]
The failing tests should actually be resolved in the next BCD update -- an attempt to fix the TypeScript definitions further broke them, but we got them seemingly working now!

**Comment by queengooborg** [comment]
The failing tests should actually be resolved in the next BCD update -- an attempt to fix the TypeScript definitions further broke them, but we got them seemingly working now!

**Comment by fiji-flo** [comment]
@queengooborg could we do a one-off bcd release to fix this? Otherwise tests will fail or we have even more outdated bcd data.

**Comment by queengooborg** [comment]
I'm planning on making another release on Friday which will include the fix, yeah!

**Comment by fiji-flo** [comment]
resolved via #6556

**Pull request closed without merging**
