### PR TITLE
helpful links on 404 page

### LINKED ISSUE #3931: Update HTTP 404 page
Please update the HTTP 404 page as show:

> You've followed a link to a page that doesn't exist.
> 
> The page might not have been written yet or may have been deleted. It is also possible that the link URL is incorrect.
> We recommend searching for similar topics on MDN.
>
> To create this page, or just fix the link, please follow our instructions on [content repo README.md](https://github.com/mdn/content#contributing-to-the-content-of-mdn-web-docs)

This follows discussion here: https://github.com/mdn/yari/discussions/3890

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #3931

What it looks like:
Screen Shot 2021-06-03 at 3 44 49 PM

And if it's a non-en-US that can find the en-US equivalent:
Screen Shot 2021-06-03 at 3 45 29 PM

To test this locally, with Yari, you do `yarn dev` and can go to <HTTP://localhost:3000/en-US/_404> or start Yari and use http://localhost:5000/en-US/docs/WHATEVER

### CODE REVIEW

**Comment by peterbe** [comment]
CC @wbamberg @hamishwillee 

I just copied, verbatim, [what Hamish suggested here](https://github.com/mdn/yari/issues/3931#issuecomment-853440653).

**Review by hamishwillee — APPROVED** [review]
FWIW I am very happy with this and I think it should be merged as-is on the basis it is a significant improvement. 

My only thought was that if I was German I would want to see all this text in German:

image

**Comment by peterbe** [comment]
Actually, mentioning German is funny because I realize a "bug" in this. The de pages are not maintained. You can't file an issue, because there is no team of reviewers for de. 
So it would be weird to combine that message with the hopelessness of "invalid locales" (for some reason, that's what we call locales that exist but not open for PRs).

**Comment by hamishwillee** [comment]
Ha :-). I'm sure you get my point. To avoid ambiguity - very happy with the text and "approach" so would be pleased if it is merged. But as a post-process there needs to be some thinking about making this work for non-English locales!

**Comment by Rumyra** [comment]
Are there redirects in place for any of our 'deprecated locales' (see what I did there) @peterbe ?

**Comment by peterbe** [comment]
> Are there redirects in place for any of our 'deprecated locales' (see what I did there) @peterbe ?

Yeah, that's already in place. E.g. https://developer.mozilla.org/sv-SE/docs/Web/CSS 

But let's not spend too much time on this here PR. 
First, we make the second to last sentence switch from `mdn/content` to `mdn/translated-content` depending on the active `locale`. 
For the last sentence, we can perhaps just link to `https://github.com/mdn/translated-content#readme` instead.

**Comment by caugner** [comment]
@Rumyra @hamishwillee If you still deem this useful, I can finish it up, but the text might need to be rewritten.

(Linking to mdn/content or mdn/translated-content depending on the locale should be fairly easy.)

image

**Comment by hamishwillee** [comment]
@caugner I'm still keen on this. What changes were you thinking about for the text.

**Comment by caugner** [comment]
> What changes were you thinking about for the text?

Something along these lines:

> Sorry, the page `...` could not be found.
>
> [this is where the green fallback box comes]
>
> If you followed a link to this page:
> - Maybe this page has not yet been written.
> - Maybe this content has been archived, deleted or retired [add links to archived-content / GitHub search / retired-content respectively].
> - Maybe the link was just incorrect.
>
> If you followed a link on MDN, please go back to the page and let us know using the "Report issue" link at the bottom.
> If you followed a link on another site, don't hesitate to contact whoever can update the content on that site.

We also want to avoid getting issue reports for frozen locales, and the screenshots above invite e.g. German users to report issues for broken links to German MDN pages (probably not a good idea).

**Comment by hamishwillee** [comment]
With respect to translated content, I have no real comment. I'd be happy in the first instance if this was applied only to English content.

With respect to the text, the original text is more succinct and took some time to agree among the team. 
If you _need_ to change it (perhaps due to the green fallback box?) then we should do another round of review. But you've certainly go the main points. A possible option that is slightly more to my taste:

> Sorry, we could not find the page: Xxxx
> 
> [this is where the green fallback box comes]
> 
> The page may be missing because it has not been written, or because it has been [archived], [deleted] or [retired].
> It is also possible that the link URL was wrong (try searching for the page name).
> 
> If you followed a link on MDN, please go back to the page and let us know using the "Report issue" link at the bottom.
> If you followed a link on another site, please contact the administrator of that site.

**Comment by caugner** [comment]
@hamishwillee See also: https://github.com/mdn/yari/pull/7070

**Comment by caugner** [comment]
Closing in favor of https://github.com/mdn/yari/pull/7070 (already merged).

**Pull request closed without merging**
