### PR TITLE
add toc styling

### LINKED ISSUE #1142: Add new TOC to reference and styling
Add new TOC component.

### Acceptance criteria
- [ ] Add TOC component to Storybook
- [ ] Implement TOC component in Yari

### PR DESCRIPTION
**Pull request by schalkneethling**
Add styling for the new table of contents aka "jump to section"

@peterbe Do not worry too much about testing this in a browser. Something is seriously 💩 up with the responsiveness of the site/page in general so, if the code looks good, let's merge so I can take a step back and see what is going on there.

fix #1142

### CODE REVIEW

**Comment by peterbe** [comment]
This is what I see:
Screen Shot 2020-09-14 at 4 22 19 PM

No toolbar :(
I know that `!isServer && CRUD_MODE && !doc.isArchive` so it should include that compontent. But it's not showing up. 
Did you see a Toolbar when you tested it yourself?

**Comment by peterbe** [comment]
Ah. It's at the bottom of the page:
Screen Shot 2020-09-14 at 4 24 49 PM

I guess it's there but it looks like 💩 so it's really hard to really review.

**Comment by peterbe** [comment]
It might be immaterial but that little black triangle isn't changing when you expand and collapse the "Jump to section" menu and I think that looks bad. Can we please fix that before we land this?

Screen Shot 2020-09-14 at 4 26 08 PM

Screen Shot 2020-09-14 at 4 26 16 PM

Also, it's hard to review with all that crazy grid stuff and inside horizontal scrolling :)
Screen Shot 2020-09-14 at 4 26 30 PM

**Review by peterbe — COMMENTED** [review]
The failure of the little caret triangle icon not changing direction when you open and close, is bad but if it's really hard to do, perhaps do it later. 

Also, having the toolbar working is nice but do you really want to land this into the mdn-fiori branch when it's unable to render at the top of the document?

**Comment by schalkneethling** [comment]
> Also, having the toolbar working is nice but do you really want to land this into the mdn-fiori branch when it's unable to render at the top of the document?

It is fine for now. I have set `CRUD` to off for me for now so the toolbar does not show at all. For right now, that is "ok" as I do have it on the roadmap to address.

**Comment by schalkneethling** [comment]
Thank you for the review @peterbe! I have addressed the issue with regards to the arrow between expanded and collapsed state. With that, I am going to merge this and jump into fixing the big responsiveness mess.

It seems related to the main content missing a lot of its styling, specifically around those `pre` and `code` blocks. More pull requests incoming.

**Pull request merged**
