### PR TITLE
add Korean translation to SeeCompatTable

### PR DESCRIPTION
**Pull request by SnowMarble**
## Summary

adding Korean translation to SeeCompatTable

안녕하세요, @hochan222 님, 리뷰 부탁드려도 괜찮을까요?

### CODE REVIEW

**Comment by hochan222** [comment]
LGTM for ko-locale-team :)


cc @mdn/core-yari-content

**Review by hochan222 — APPROVED** [review]

**Review by bsmth — CHANGES_REQUESTED** [review]
Thanks a lot! the changes look good, but the commit has to be signed, please see https://github.com/mdn/yari/actions/runs/5971616180/job/16266782277?pr=9548

If you need some help with this, see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits or let us know if you're stuck!

**Comment by SnowMarble** [comment]
@bsmth Thanks for letting me know. I've done updating the commit.

**Review by bsmth — APPROVED** [review]
Thank you!

**Pull request merged**
