### PR TITLE
chore(macros): remove unused Link macro

### PR DESCRIPTION
**Pull request by MrBrain295**
## Summary
There are no remaining occurrences of the `link` macro in translated content.

### Problem
It’s not needed.

### Solution
Delete it.

---

## Screenshots
N/a

### Before
N/a

### After
N/a

---

## How did you test this change?
N/a

### CODE REVIEW

**Comment by yin1999** [comment]
The macro removal has been tracked in mdn/translated-content#7566. Confirmed by `rg`:

image

**Comment by MrBrain295** [comment]
@caugner

**Comment by fiji-flo** [comment]
https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/typed_arrays/index.md still has a `link` marco.

Did that get added in the meanwhile? Sorry for missing this.

**Comment by yin1999** [comment]
> Did that get added in the meanwhile? Sorry for missing this.

Maybe this PR: mdn/translated-content#8200

**Comment by caugner** [comment]
Converting to draft until new `{{Link}}` occurrences in translated-content are removed again:

```
% rg -i '\{\{\s*link' content translated-content                                                                                                                                                                                                                          1 ↵
content/files/en-us/mdn/writing_guidelines/page_structures/macros/deprecated_macros/index.md
14:## The \{{Link}} macro
25:The \{{Link("/en-US/docs/Web/JavaScript/Guide/Numbers_and_dates")}} page on MDN

translated-content/files/es/web/javascript/typed_arrays/index.md
55:- {{Link("/en-US/docs/Web/API/FileReader", "FileReader.prototype.readAsArrayBuffer()", "#readAsArrayBuffer()")}}
56:  - : El método `FileReader.prototype.readAsArrayBuffer()` comienza a leer el contenido del {{Link("/es/docs/Web/API/Blob", "Blob")}} o {{Link("/es/docs/Web/API/File", "File")}}.
59:- {{Link("/en-US/docs/Web/API/ImageData", "ImageData.data")}}
125:Al combinar un solo búfer con múltiples vistas de diferentes tipos, comenzando con diferentes desplazamientos en el búfer, puedes interactuar con objetos de datos que contienen múltiples tipos de datos. Esto te permite, por ejemplo, interactuar con complejas estructuras de datos {{Link("/es/docs/Web/WebGL", "WebGL")}}, archivos de datos o estructuras C que necesitas utilizar mientras usas {{Link("/en-US/docs/Mozilla/js-ctypes", "js-ctypes")}}.
```

**Comment by MrBrain295** [comment]
The pr got merged so I think this one is ready.

**Review by caugner — APPROVED** [review]

**Pull request merged**
