### PR TITLE
Updating contact picker

### PR DESCRIPTION
**Pull request by Rumyra**
It's a singular 'Contact Picker API' - it was added as 'Contact*s* Picker API'

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
Good point!

**Comment by chrisdavidmills** [comment]
Ah, dammnit, we've got a test failure, and I don't know how to fix this.

**Comment by Rumyra** [comment]
I literally can _not_ see why those changes would fail - could it be I did it through the gh interface and there's some sort of character/encoding something??

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/pulls?q=nonExistentMacro

**Comment by chrisdavidmills** [comment]
Any thoughts on why this failing @escattone @peterbe ?

**Comment by peterbe** [comment]
The errors don't appear to be related. 

What probably happened was that we changed something that affects the kumascript test suite but when we made that change, the unit tests weren't run. 
It could also be, for example, that no change was made to any of the files `kumascript/**` but one of the testing libraries changed. 

I'll try to fix it and then we can merge in `master` into this PR and try again.

**Comment by peterbe** [comment]
@Rumyra do you think you can merge in the latest `master` into your branch? Then all the tests will pass. 
If that's a hassle, we can just merge this.

**Comment by peterbe** [comment]
Could this be the explanation for https://github.com/mdn/yari/issues/2293 ?

**Comment by Rumyra** [comment]
Hi @peterbe - absolutely.

Just to clarify, if I've understood correctly this took on an extra space error from a previous pr because I used the web ui?

**Comment by peterbe** [comment]
> Just to clarify, if I've understood correctly this took on an extra space error from a previous pr because I used the web ui?

Sorry. I don't understand. What "extra space error"?

**Comment by peterbe** [comment]
Our version of `cheerio` got upgraded (rc-3 to rc-5) and that upgrade snook in without running the kumascript unit test suite (which kinda makes sense kinda). There was a big difference in that cheerio upgrade that affects how HTML is serialized.

**Pull request merged**
