### PR TITLE
Help when the CONTENT_ROOT lacks the "files" ending

### LINKED ISSUE #2248: Help when the CONTENT_ROOT lacks the "files" ending
At least two people have been tripped up by this now. 
E.g. You have a folder called `/path/to/mdn/content` which is a checkout of github.com/mdn/content so you think you can do:
```bash
export CONTENT_ROOT=/path/to/mdn/content
```
but if you do that, you'll get quite weird errors. The solution is to use:
```bash
export CONTENT_ROOT=/path/to/mdn/content/files
```
which isn't intuitive. We can pretty easily write some code around that constant that can either warn or just re-set it (and warn).

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #2248

### CODE REVIEW

**Comment by peterbe** [comment]
here's how I tested it:
```
export CONTENT_ROOT=/Users/peterbe/dev/MOZILLA/MDN/content
yarn dev
```
then I see, in the logging:
```
Corrected the CONTENT_ROOT environment variable to /Users/peterbe/dev/MOZILLA/MDN/content/files
...
2:14:03 PM server.1     |  CONTENT_ROOT: /Users/peterbe/dev/MOZILLA/MDN/content/files
```

**Comment by mattiapontonio** [comment]
Does update the readme solve this issue...? Something that make clear that files Is a subfolder....

**Comment by peterbe** [comment]
Actually @ugultopu Can you test this PR and see if it solves the steps in https://github.com/mdn/yari/issues/2638

**Comment by ugultopu** [comment]
@peterbe Yep, works now.

**Review by nschonni — APPROVED** [review]

**Pull request merged**
