### PR TITLE
include native name for translations

### PR DESCRIPTION
**Pull request by peterbe**
Part of #2877

How to test:

```
# or whatever you have in your .env on your system
export CONTENT_TRANSLATED_ROOT=~/dev/MOZILLA/MDN/translated-content-rendered/files

BUILD_FOLDERSEARCH=web/html/element/section yarn build
yarn start
```
Now, visit http://localhost:5000/en-US/docs/Web/HTML/element/section/index.json and http://localhost:5000/hu/docs/Web/HTML/element/section/index.json and you'll see that for each listed `translations` there's a new key `native`. 

With this in place, the language dropdown does not need to load in `languages.json` into the JS bundle because it's part of the JSON data. So basically no need to convert `fr` to `Français` in the client. 

This is currently a draft because I know @schalkneethling is working on some big refactoring of the language menu. 

Also, any day now we'll be able to drop the `url` for each entry in the `translations` because the URL will always be whatever the current "slug" is + the `locale`.

### CODE REVIEW

**Comment by peterbe** [comment]
It worked! Now there's no bloated `languages.json` part of the main JS bundle.
Screen Shot 2021-03-09 at 4 06 21 PM

**Comment by schalkneethling** [comment]
> BUILD_FOLDERSEARCH=web/html/element/section yarn build

@peterbe I am getting the following when running this:

```
TypeError: Cannot read property 'pathname' of undefined
    at N (/Users/schalkneethling/repos/yari/ssr/dist/main.js:1:12754)
    at /Users/schalkneethling/repos/yari/ssr/dist/main.js:1:9671
    at Object.re [as useMemo] (/Users/schalkneethling/repos/yari/ssr/dist/main.js:30:7993)
    at t.useMemo (/Users/schalkneethling/repos/yari/ssr/dist/main.js:14:5741)
    at v (/Users/schalkneethling/repos/yari/ssr/dist/main.js:1:9651)
    at R (/Users/schalkneethling/repos/yari/ssr/dist/main.js:1:13649)
    at Object.render (/Users/schalkneethling/repos/yari/ssr/dist/main.js:1:4718)
    at e.t.render (/Users/schalkneethling/repos/yari/ssr/dist/main.js:30:15377)
    at e.t.read (/Users/schalkneethling/repos/yari/ssr/dist/main.js:30:14283)
    at t.renderToString (/Users/schalkneethling/repos/yari/ssr/dist/main.js:30:19841)
```

**Comment by peterbe** [comment]
> BUILD_FOLDERSEARCH=web/html/element/section yarn build

Doesn't happen to me. When you run that `yarn build` it usually prints out some info about all the "Building roots". 
Are they all correct and sane?

**Comment by schalkneethling** [comment]
> > BUILD_FOLDERSEARCH=web/html/element/section yarn build
> 
> Doesn't happen to me. When you run that `yarn build` it usually prints out some info about all the "Building roots".
> Are they all correct and sane?

Going to give this a go again.

**Review by schalkneethling — APPROVED** [review]
🧹 🎉 - Thanks, @peterbe

**Pull request merged**
