### PR TITLE
Fixes #777

### LINKED ISSUE #777: A link in Demos of Open web technologies refers to 'Page not found (404)'.
The link provided in the mdn docs leads to a 'Page not found'. The page which this link refers does not exist. So, please remove this link from the MDN web docs.
https://github.com/mdn/yari/blob/master/content/files/en-us/web/demos_of_open_web_technologies/index.html#L28

### PR DESCRIPTION
**Pull request by anirudhganwal06**
Removed 'Flying from space' link from demos of open web technologies

### CODE REVIEW

**Comment by anirudhganwal06** [comment]
Fixes Issue: #778

**Comment by peterbe** [comment]
@anirudhganwal06 How did you manage to create a PR from a `unknown repository`?

Also, what is the motivation for this change?

**Comment by anirudhganwal06** [comment]
- I forked this repo to anirudhganwal06/yari.
- I commited to my forked repo.
- I made a pull request to mdn/yari.
- Then, I deleted my forked repo.
This is the reason it's showing `unknown repository`.

## Motivation
I was going through the docs and I saw that this link to a github page is giving a 404 error. The github user must have removed the repo or have disabled github pages.
So, I thought it would be a bad experience for someone crawling through the official docs and find that the links provided are broken.

**Comment by peterbe** [comment]
The content inside this repo is actually a clone of the data we use in `developer.mozilla.org` which is an AWS RDS MySQL server. The files here in this repo is just a snapshot of that. So a change like this PR, even though it was a worthwhile exercise, will just get overwritten. 

The page to actually go and fix is: https://wiki.developer.mozilla.org/en-US/docs/Web/Demos_of_open_web_technologies

Within Yari we hope we can automate away these kinds of things. In the initial version, we're working on some rock-solid link validation for *internal* links that don't require a network check.

**Pull request closed without merging**
