### PR TITLE
Add contact detail

### PR DESCRIPTION
**Pull request by iamVP7**
Added contact detail got from [MDN  hacks post](https://hacks.mozilla.org/2020/10/mdn-web-docs-editorial-strategy-and-community-participation/).

### CODE REVIEW

**Comment by peterbe** [comment]
@iamVP7 Thanks for starting this! The README.md has since changed. Would you mind merging in `master` into your brancha and resolve the conflict?

**Comment by peterbe** [comment]
@iamVP7 ping. Would you mind merging in the latest upstream `main` into your branch. Or perhaps start a fresh new PR with this nice change.

**Comment by KartikSoneji** [comment]
I agree, having the developer chat in the readme is quite handy, just spent ~20 minutes looking for it.
@iamVP7 if you don't have the time then I don't mind opening an updated PR.

**Comment by iamVP7** [comment]
Hey @KartikSoneji  kindly send PR. Sorry Not able to focus on this now.

**Comment by KartikSoneji** [comment]
@iamVP7 thanks, I have opened an updated PR: #4743.

**Pull request closed without merging**
