### PR TITLE
EmbedLiveSample breaks if ID has non-ASCII

### PR DESCRIPTION
**Pull request by peterbe**
Part of #3598

@escattone This is a draft because, at the time of writing, all it does is demonstrate the problem. 
Perhaps I'm completely off, but this seems like a reasonable input:
```
<h3 id="Fire🔥">Heading</h3>
<pre class="brush: css">blink {
  color: maroon;
}</pre>
<pre class="brush: html">&lt;blink&gt;hi&lt;/blink&gt;</pre>

<p>{{EmbedLiveSample('Fire🔥', '500px', '300px')}}</p>
```

Having a Unicode character in the `id="..."` value is valid. I actually sanity-checked it with the w3c validator. 
Screen Shot 2021-04-22 at 10 03 48 AM

The code there scares me a bit. I don't know exactly what's going on but I think what happens is that it uses `cssesc` to turn an slugified ID into an *escaped* slugified selector. 
So it ends up doing a (`cheerio`) search for `$('#Fire\1F525')` but the ID of the `h3` hasn't been slugified or escaped.

### CODE REVIEW

**Comment by peterbe** [comment]
Thing is, there's two separate things going on. The `cssesc` usage is probably there for a very good reason; security. 
But it seems that transform function escapes all unicode. Not just important control characters. 
Perhaps what's the root is that whatever gets done with that first input argument to the `EmbedLiveSample(THIS, ...)` macro, that needs be applied equally to all `[id]` values that already exist in the HTML.

**Comment by Ryuno-Ki** [comment]
If you are on the lookout for potentially interesting strings, take a look at https://github.com/minimaxir/big-list-of-naughty-strings
Could bring up some other edge cases :)

**Comment by peterbe** [comment]
@escattone Just so I don't forget... I pinged you on Slack about this but let's make it a priority to discuss this on video next week (starting Apr 26).

**Comment by peterbe** [comment]
Let's do https://github.com/mdn/yari/pull/3660 instead. Simpler. Much simpler.

**Pull request closed without merging**
