### PR TITLE
chore(macros/LearnSidebar): add Japanese translation

### PR DESCRIPTION
**Pull request by gurezo**
## Summary

@schalkneethling
cc @hmatrjp @potappo 
- [ Filtering our to-do items の翻訳 #623](https://github.com/mozilla-japan/translation/issues/623)  のPRです。

### Problem
still en-us only

### Solution

taranlate japanese for LearnSidebar.ejs

### Before

still en-us only

### After

add taranlate japanese for LearnSidebar.ejs

### CODE REVIEW

**Comment by potappo** [comment]
修正内容問題ありません。ありがとうございます。

LGTM Thanks!

**Comment by potappo** [comment]
t's time to poke @mdn/mdn-community-engagement .

**Comment by caugner** [comment]
@gurezo Please have a look at the failing check (your commit is not signed). 🙏

**Comment by gurezo** [comment]
> @gurezo Please have a look at the failing check (your commit is not signed). 🙏

@caugner @potappo 

I made a commit/push after creating a GPG Key on Github or terminal, but it didn't pass the workflow.
Please tell me how to solve it.

```➜  yari git:(issue/623/angular_filtering) echo 'test'|gpg --clearsign
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

test
-----BEGIN PGP SIGNATURE-----

キー情報

-----END PGP SIGNATURE-----
➜  yari git:(issue/623/angular_filtering)
```


スクリーンショット 2022-08-22 23 11 30
スクリーンショット 2022-08-22 23 23 07

**Comment by gurezo** [comment]
@caugner @potappo

i had resolved follow steps

```
➜  yari git:(issue/623/angular_filtering) git reset --hard bcc4a5617941f016d980f267b7b7d84ec43552be <== PR commit hash
HEAD is now at bcc4a5617 feat(translate): 各日本語ページリンク更新
➜  yari git:(issue/623/angular_filtering) git rebase -i a0428f3ad0e8365d21a847037b857707063d0516 <==  rebase of before commit hash
Successfully rebased and updated refs/heads/issue/623/angular_filtering.
➜  yari git:(issue/623/angular_filtering) git config --global user.signingkey キー <== config user.signingkey key
➜  yari git:(issue/623/angular_filtering) git commit --amend --no-edit -S 
[issue/623/angular_filtering 4f6a92976] feat(translate): 各日本語ページリンク更新
 Date: Sat Aug 20 22:53:21 2022 +0900
 1 file changed, 1 insertion(+), 1 deletion(-)
➜  yari git:(issue/623/angular_filtering) git push origin issue/623/angular_filtering -f <== changes force push
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 10 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 739 bytes | 739.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:gurezo/yari.git
 + a70808613...4f6a92976 issue/623/angular_filtering -> issue/623/angular_filtering (forced update)
➜  yari git:(issue/623/angular_filtering)

```

**Comment by potappo** [comment]
@caugner
Yeah, but there are a lot of words to translate at the same time... Now, I focus on converting markdown, so will work on translating the template later.

Please marge only gurezo's translations at this time.

**Pull request merged**
