### PR TITLE
Update L10n-CSS.json

### PR DESCRIPTION
**Pull request by mattiapontonio**
Added some translations.
Where are visibile if merged?

### CODE REVIEW

**Comment by mattiapontonio** [comment]
I'm feel like a good old boy indenting and spacing with my keyboard in this textarea 👌👍🎉

**Review by chrisdavidmills — APPROVED** [review]
The localizations looks good, thanks.

I don't know where these get used, to be honest.

**Comment by mattiapontonio** [comment]
Yeeee
I'm a contributor 😎



Thanks @chrisdavidmills !

**Comment by escattone** [comment]
@chrisdavidmills Just for future reference, `L10n-CSS.json` is used in the following macros:
- https://github.com/mdn/yari/blob/228cb6b08695d40dcb9e2e6deebc872694a406e2/kumascript/macros/CSSInfo.ejs#L24
- https://github.com/mdn/yari/blob/228cb6b08695d40dcb9e2e6deebc872694a406e2/kumascript/macros/CSSRef.ejs#L22
- https://github.com/mdn/yari/blob/228cb6b08695d40dcb9e2e6deebc872694a406e2/kumascript/macros/CSSSyntax.ejs#L54

**Comment by mattiapontonio** [comment]
Thanks @escattone.
How did You find them?
Here 0 reaults.
https://github.com/mdn/yari/search?q=L10n-CSS.json&type=

**Pull request merged**
