### PR TITLE
build(deps-dev): bump react from 17.0.2 to 18.1.0

### PR DESCRIPTION
**Pull request by caugner**
## Summary

Bumps react from v17 to v18.

Also bumps:
- @testing-library/react from 12.1.5 to 13.2.0
- @types/react from 17.0.45 to 18.0.9
- @types/react-dom from 17.0.16 to 18.0.3
- react-dom from 17.0.2 to 18.1.0

See:
- [reactjs.org: _React v18.0_](https://reactjs.org/blog/2022/03/29/react-v18.html)
- [reactjs.org: _How to Upgrade to React 18_](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)
- [github.com/facebook/react: _v18.0.0_](https://github.com/facebook/react/releases/tag/v18.0.0)

---

## Screenshots

_Not applicable._

---

## How did you test this change?

_Not yet._

### CODE REVIEW

**Comment by caugner** [comment]
Currently stuck on this error:

image


```
TS2786: 'ReactModal' cannot be used as a JSX component.
  Its instance type 'ReactModal' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/Users/claas/github/mdn/yari/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
    11 | export default function MDNModal(props: ModalProps) {
    12 |   return (
  > 13 |     <ReactModal
       |      ^^^^^^^^^^
    14 |       overlayClassName="modal-overlay"
    15 |       className={`modal-content ${props.className || ""} ${
    16 |         props.size ? `is-${props.size}` : ""
```

**Comment by caugner** [comment]
> Currently stuck on this error:

Okay, [this](https://stackoverflow.com/a/71835812) might have given me a lead:
```
% yarn why @types/react                                                                                                                                                           1 ↵ ✹
yarn why v1.22.18
[1/4] 🤔  Why do we have the module "@types/react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/react@18.0.9"
info Has been hoisted to "@types/react"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "196KB"
info Disk size with unique dependencies: "1.32MB"
info Disk size with transitive dependencies: "1.32MB"
info Number of shared dependencies: 3
=> Found "@types/react-dom#@types/react@17.0.45"
info This module exists because "@types#react-dom" depends on it.
info Disk size without dependencies: "184KB"
info Disk size with unique dependencies: "1.31MB"
info Disk size with transitive dependencies: "1.31MB"
info Number of shared dependencies: 3
=> Found "@types/react-modal#@types/react@17.0.45"
info This module exists because "@types#react-modal" depends on it.
info Disk size without dependencies: "184KB"
info Disk size with unique dependencies: "1.31MB"
info Disk size with transitive dependencies: "1.31MB"
info Number of shared dependencies: 3
✨  Done in 0.64s.
```

**Comment by caugner** [comment]
🔃 Triggered a [dev build](https://github.com/mdn/yari/actions/runs/2307809731) that will deploy pr6235.content.dev.mdn.mozit.cloud/.

**Comment by caugner** [comment]
🔃 Waiting for #6244 and #6246 to land, in order to easier debug the test failures...

**Comment by caugner** [comment]
🔃 Triggered a [dev build](https://github.com/mdn/yari/actions/runs/2309150397) which will deploy [here](https://pr6235.content.dev.mdn.mozit.cloud/).

**Comment by caugner** [comment]
Unfortunately navigation in the Plus docs seems to be broken:

1. Open https://pr6235.content.dev.mdn.mozit.cloud/en-US/plus/docs/faq
2. Click on "MDN Offline" in the left sidebar.

🤔

**Comment by caugner** [comment]
@mirunacurtean If you have some time, it would be great if you could test https://pr6235.content.dev.mdn.mozit.cloud/ for any UI regressions in comparison to https://developer.mozilla.org/. 🙏

**Comment by mirunacurtean** [comment]
> @mirunacurtean If you have some time, it would be great if you could test https://pr6235.content.dev.mdn.mozit.cloud/ for any UI regressions in comparison to https://developer.mozilla.org/. 🙏

Sure. I'll update with the results.

**Comment by mirunacurtean** [comment]
@caugner I'm still testing but so far I noticed that the Edit and Source on Github links are redirected to a 404 page instead or the authentication page in comparison to the "report a problem.." link. 
Edit and Source pages not found instead of requiring authentication

**Comment by caugner** [comment]
> I'm still testing but so far I noticed that the Edit and Source on Github links are redirected to a 404 page instead or the authentication page in comparison to the "report a problem.." link.

Good catch, but I think that's just an artifact of our dev build, which is also used for PRs on mdn/content, where the links would go to the PR branch. 🙂

**Comment by mirunacurtean** [comment]
Short summary, no new issues found. 
Detailed summary. 
Top navigation looks and behaves the same as in production. Search functionality remains the same (focus, search through text or symbols, delete input). 
Theme switch is applied through menu or through OS personalization. No no issues have been introduced in homepage or top navigation search (404 issues through [search](https://github.com/mdn/yari/issues/4615) and [Back action](https://github.com/mdn/yari/issues/6161) withstanding) 
Article Actions on Desktop lists article breadcrumbs and the language selector that applies the language change successfully. On mobile the menu opens and is closed as a result of the applied language change.Breadcrumb redirects are successful.  No display issues. 
Sidebar navigation in desktop and mobile behaves with no issues (open/ close, Scroll, expand topics and select items)
No new issues have cropped out when using TOC navigation of an article or the in between article Next/ Overview/Previous buttons and in-article links. 

Interactive examples and code snippets are displayed and functional:
Example:
https://pr6235.content.dev.mdn.mozit.cloud/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

Deprecated, Warning and Notes elements look the same as compared to production.
In article links or references to pages outside MDN work as expected. 
Example:
https://pr6235.content.dev.mdn.mozit.cloud/en-US/docs/Learn/Accessibility/What_is_accessibility#accessibility_guidelines_and_the_law
https://pr6235.content.dev.mdn.mozit.cloud/en-US/docs/Learn/Accessibility

No no issues with tables either: 
https://pr6235.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/TreeWalker
https://pr6235.content.dev.mdn.mozit.cloud/en-US/docs/web/api/ui_events/keyboard_event_key_values#numeric_keypad_keys

"Found a problem with this page?" and footer links are working (outside the case in the previous comment which is a non-issue).

With MDN Plus the Learn more links redirect to the last accessed MDN Plus page and the[ MDN Plus menu is not working](https://github.com/mdn/yari/issues/6253) but the Notifications, Collections and MDN Offline pages are loaded through the https://pr6235.content.dev.mdn.mozit.cloud/en-US/plus/docs/faq article links. So I've at least checked that back and forth navigation betweehn pages and In this Article selection are functional.

**Review by LeoMcA — APPROVED** [review]
all these changes look fine, I had a look over the react 18 release notes as well, and couldn't see anything you've missed

**Comment by caugner** [comment]
Thank you @LeoMcA! 🙏

**Pull request merged**
