### PR TITLE
actually call 'deployer search-index' in dev and stage

### PR DESCRIPTION
**Pull request by peterbe**
Part of #2410

### CODE REVIEW

**Comment by peterbe** [comment]
[I kicked one off for Dev](https://github.com/mdn/yari/actions/runs/482990516). We'll see in about an hour if it populated the `DEPLOYER_DEV_ELASTICSEARCH_URL`.

**Comment by peterbe** [comment]
[It worked! On dev](https://github.com/mdn/yari/runs/1695622967?check_suite_focus=true)

```
Found 50,341 (potential) documents to index
Deleting any possible existing index and creating a new one called mdn_docs
Took 2m 52s to index 50,276 documents. Approximately 291.2 docs/second
```

Now, I haven't actually tried to *use* the data indexed but that's a battle for another hour.

**Comment by peterbe** [comment]
[Here's an attempt to build Stage](https://github.com/mdn/yari/actions/runs/483143850) 
At the time of running, it hasn't finished yet.

**Comment by peterbe** [comment]
Worked in Stage too!
```
 Found 50,341 (potential) documents to index
Deleting any possible existing index and creating a new one called mdn_docs
Took 3m 49s to index 50,276 documents. Approximately 219.3 docs/second
Counts per priority prefixes:
	en-us/docs/web                 8,992
	*rest*                         41,284
```

**Review by escattone — APPROVED** [review]
Looks good, let's try it!

**Pull request merged**
