### PR TITLE
Top level await

### PR DESCRIPTION
**Pull request by Rumyra**
Adding the top level await spec to specdata.json

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@Elchi3 please can you review this one?

**Review by Elchi3 — APPROVED** [review]

**Comment by Elchi3** [comment]
Approving but can't merge:

> Merging is blocked. The base branch requires all commits to be signed. 

[Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)

**Comment by mattiapontonio** [comment]
FTR
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by chrisdavidmills** [comment]
Bah, let's get this one merged. I've not managed to get my commit signing set up yet either.

**Comment by mattiapontonio** [comment]
> I've not managed to get my commit signing set up yet either.

Me too.

---

My personal interpretation of this is to make small changes directly from the web. This also helps in getting points to win the race 🏎️🏅.

**Comment by Ryuno-Ki** [comment]
> Bah, let's get this one merged. I've not managed to get my commit signing set up yet either.

I just did so today. Took me ~10min ;-)
Including generating a new GPG key.

**Comment by chrisdavidmills** [comment]
> > Bah, let's get this one merged. I've not managed to get my commit signing set up yet either.
> 
> I just did so today. Took me ~10min ;-)
> Including generating a new GPG key.

I've gone through the process before, and have got a GPG key set up on my GitHub. But it still doesn't recognise me as signed, for some reason. It kind of worked for bit, and then dropped again, and I just don't have time to mess with it.

**Comment by peterbe** [comment]
It's so annoying that it's so hard to set up! Clearly, it's ruining productivity. 
The thing to watch out for, when commits are not signed, is that the commits might *appear* to be made from someone you trust so you don't scrutinize. So a rogue actor could make you think the edit is harmless because it's a well-known contributor, but in fact it's sneaking in some harmful edit (e.g. spam, security breakage). 
So if you see a PR where the commits aren't signed; just a little bit more carefully click the "Files" tab and make sure nothing weird is put in.

**Comment by Ryuno-Ki** [comment]
>  So if you see a PR where the commits aren't signed; just a little bit more carefully click the "Files" tab and make sure nothing weird is put in.

Wait, you don't accept PRs blindly, do you? O_o

What's hard to me, is that my `git log` is not showing me signature checks by default. (I'm used to use signed-of-by in my commits, but that's something different and also prone to be spoofed).

**Pull request merged**
