### PR TITLE
chore: Add pylint for deployer

### PR DESCRIPTION
**Pull request by nschonni**
- Add package through poetry
- Generate RC file and turn off all existing issues
- Add call in CI

### CODE REVIEW

**Comment by nschonni** [comment]
@peterbe @escattone I added it to the `testing/integration` but I didn't see that code being called or tested in CI currently

**Comment by peterbe** [comment]
What does `pylint` add that `flake8` and `black` doesn't already cover?

**Comment by nschonni** [comment]
Not a python expert, but flake8 wraps pyflakes which says https://github.com/PyCQA/pyflakes#design-principles
Black is more of "prettier" formatter rather than a linter AFAIK
Each cover aspects the others don't

**Comment by peterbe** [comment]
No, I'm not interested in what `pylint` offers on top of `flake8`. Yes, seems that `pylint` checks some things like `flake8` lets you miss. Things that `pylint` offers are things like complaining about your variable name choices. I'm not sure we're suffering in that. And `pylint` has stuff that relates to the style which is something I think `black` should be allowed to handle 100%. `flake8` doesn't go near styling. So that makes the companionship of `flake8` + `black` great. 
Another thing I don't like about `pylint` is the enormousness of the config file. Thing is, I don't want to configure things. In fact, I think we're sticking to the defaults apart from a couple of overrides that we copy and pasted from the `black` documentation. 
```
max-line-length=88
ignore = E203, E501, W503
```
I don't think these overrides reflect any personal quirky preferences of the team, but just "boilerplate" you need to chuck in if you want to do the `black` + `flake8` combo. 
But avoiding config overrides we can be as close as we possibly can to being right in the middle of a normalized curve. Now, we're like almost all other Python projects and not being "weird". Basically, I think we should NOT be picky and follow popular ling/styling rules that the masses of open source projects follow. That makes it more likely that people look at our code and not be distracted by "un-conventions" that are team specific. 

Do you mind if we close this? 
Perhaps @escattone would like to share his mind too?

**Comment by escattone** [comment]
Sorry @nschonni, I agree with @peterbe here. I'd rather not add `pylint` to our mix. I think `flake8` covers us well enough.

**Comment by escattone** [comment]
Thanks for your care and effort in working on this @nschonni, but I think we're going pass on this PR.

**Pull request closed without merging**
