### PR TITLE
chore: remove ServiceWorkerSidebar

### PR DESCRIPTION
**Pull request by nschonni**
## Summary

All references have been removed from content/translated-content https://github.com/orgs/mdn/discussions/263#discussioncomment-4743530

### Solution

---

### After

---

### CODE REVIEW

**Review by LeoMcA — APPROVED** [review]
Nice! Can we remove this reference as well?

https://github.com/mdn/yari/blob/517d562664ffa581b5d333121514477cf386f0f5/content/translation.ts#L61

**Comment by nschonni** [comment]
@LeoMcA good call, I also removed the `ToolsSidebar` that was also handing around.

//cc @MrBrain295 since you also seem to clean out the macros regularly

**Review by MrBrain295 — APPROVED** [review]
LGTM

**Comment by nschonni** [comment]
I think https://github.com/mdn/content/pull/23849 should resolve the unrelated CI failure that came from renaming the files with braces upstream today

**Comment by nschonni** [comment]
The unrelated Kitchensink failure has been fixed, so this should be OK to land now

**Pull request merged**
