### PR TITLE
chore(macros/HTTPSidebar): update Chinese translation + translate CSP item

### PR DESCRIPTION
**Pull request by fwqaaq**
## Summary

Update Chinese translation and field of HTTPSiderbar macros.

Many contries have translated the `CSP` field, but I'm from China, sorry I can only fix Chinese `CSP` field.

It looks good

### Solution

---

## Screenshots

image

### After

---

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for zh-CN translation (Not sure about the new item added here)

**Comment by yin1999** [comment]
Hi @fwqaaq, the screenshot image is broken, and please place it under **Screenshots**

**Comment by fwqaaq** [comment]
> Hi @fwqaaq, the screenshot image is broken, and please place it under **Screenshots**

👌

**Comment by caugner** [comment]
@fwqaaq To fix the tests, please make sure to sign your commit (see [the instructions in the failing test](https://github.com/mdn/yari/actions/runs/4827510638/jobs/8715472122?pr=8727#step:5:30)) and rebase your PR on the latest `main` (which has a fix for the failing kumascript unit test).

**Comment by fwqaaq** [comment]
@caugner  Maybe something like this? There should be no problems with my operations? I'm sorry if it causes problems, `gnupg` under mac is really hard to use.

**Comment by yin1999** [comment]
> `gnupg` under mac is really hard to use.

Try [SSH commit signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification). This is much easier and is supported by GitHub.

**Review by caugner — APPROVED** [review]

**Pull request merged**
