### PR TITLE
fix:search - always show search expanded in header

### LINKED ISSUE #5368: UI suggestion: The search box expands by default for new website
## What is the new suggestion?

The search box expands by default

## Why is it important or useful?

I come for search something

## Other supporting information

I'm having trouble with the new website design. Even with the improvements, the search box is still too small.

### LINKED ISSUE #5493: UI/UX Issue: Search is now hidden behind a button
MDN URL: https://developer.mozilla.org/en-US/docs/Web

#### What information was incorrect, unhelpful, or incomplete?

Search usability has been reduced: Search input is now hidden behind a button where it used to be at the top of the page.

Part of the usefulness of MDN docs before the UI change was being able to easily search at any time, now that is harder to do. Hiding core functionality behind a button drastically reduces usability.

How to fix: Keep the search input available at all times, don't hide it behind a button. (ex: see github.com);

#### Specific section or headline?

Main Nav Search button

#### What did you expect to see?

A search bar at the top of the page.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/index.md
* Last commit: https://github.com/mdn/content/commit/f33c6f2cc126e9fe2d2968c12291e8b6a8f322df
* Document last modified: 2022-03-02T06:46:41.000Z

</details>

### PR DESCRIPTION
**Pull request by schalkneethling**
~~Always show the search input as expanded in the header.~~

See https://github.com/mdn/yari/pull/5507#issuecomment-1069417513 for details on how this component will function

fix #5493
fix #5368

### CODE REVIEW

**Comment by schalkneethling** [comment]
@caugner I will attend to this one today and make the updates we discussed yesterday.

**Review by caugner — COMMENTED** [review]
As outlined by @fiji-flo yesterday, the idea is to always show the search input, and to make it look

- collapsed when empty (or `:invalid`)
- expanded when focused or non-empty

Florian pointed out that the search field on the front page does something similar to show the blinking cursor.

**Comment by schalkneethling** [comment]
@caugner Ready for review:

https://user-images.githubusercontent.com/10350960/158614789-31cab663-152f-4b04-8624-3e18ad261cab.mov

**Comment by schalkneethling** [comment]
@caugner addressing the two failing tests.

**Comment by schalkneethling** [comment]
@caugner Ok, the way it works now is as follows:

- If the search input receives focus(either by clicking, tabbing to the field, or pressing `/`) the field will expand
- If the input field is empty and a reader presses the escape key or clicks outside the field, it will collapse
- If the reader types into the search field and presses escape, it will clear out the field and collapse
- If the reader typed into the search field and clicks outside, the field will remain expanded and the results dropdown will remain open

**Review by caugner — COMMENTED** [review]
Looks great, especially on desktop, thanks @schalkneethling!

Having said this, on mobile the search field and the search icon are a bit far from each other:
Screenshot 2022-03-16 at 21 13 38

> 1. If the search input receives focus(either by clicking, tabbing to the field, or pressing `/`) the field will expand
> 2. If the input field is empty and a reader presses the escape key or clicks outside the field, it will collapse
> 3. If the reader types into the search field and presses escape, it will clear out the field and collapse

Tested those all, but I'm not sure about this one:

> 4\. If the reader typed into the search field and clicks outside, the field will remain expanded and the results dropdown will remain open

I would expect the search results to close when clicking somewhere else, although I know that this PR didn't change the behavior. But without the close button, it could be an issue on mobile. Have we considered adding the close button inside the field, to the left of the search icon? Or, if that's not an option, would it be a compromise to add the close button back on mobile?

**Comment by schalkneethling** [comment]
> Having said this, on mobile the search field and the search icon are a bit far from each other:

My bad :(

**Comment by schalkneethling** [comment]
> Tested those all, but I'm not sure about this one

Yeah, I also do not feel great about this one but, as long as there are results, it will stay in this state. Let me try out your suggestion and update the PR

**Review by caugner — APPROVED** [review]

**Pull request merged**
