### PR TITLE
fix: make tables scrollable on mobiles

### PR DESCRIPTION
**Pull request by lex111**
### Problem

Tables on mobile devices are not scrollable.

### Solution

Allow horizontal scrolling for tables on mobiles

---

### Before

image

### After

image

---

## How did you test this change?

1. Use https://developer.mozilla.org/en-US/docs/Web/Performance/Navigation_and_resource_timings as test page

### CODE REVIEW

**Review by caugner — APPROVED** [review]
Good catch, thank you! 🎉

**Review by caugner — COMMENTED** [review]
@lex111 Can you specify in which mobile browser you couldn't scroll the table on https://developer.mozilla.org/en-US/docs/Web/Performance/Navigation_and_resource_timings?

I opened it in Firefox for Android and had no problems scrolling it.

**Comment by lex111** [comment]
In Chrome browser on my Android phone, I ran into this problem.

**Comment by caugner** [comment]
Thank you, I was able to reproduce the issue with Chrome, and verified the fix.

**Pull request merged**
