### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mattiapontonio**
https://github.com/mdn/yari/issues/2901

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
This change makes no sense. The content in between slashes are supposed to be indicating a placeholder directory path.

**Comment by mattiapontonio** [comment]
It wasn't clear. Even better would be to use _root_ and the scripts that use the variable CONTENT_ROOT use the `files` folder but it's way too complicated for me.
Who knows if content changes folders. It would be content that should officially expose some API in the root.

**Comment by chrisdavidmills** [comment]
> It wasn't clear.

OK, this is more useful. It would have been better for you to start with this, plus an extended description of what isn't clear, and why. And then we could have a discussion about the best course of action to fix this problem.

As it was, I just got a PR with a change, with made no sense given the lack of explanation, so I closed it.

I'm afraid I don't really understand the rest of your message, so I'm just going to focus on making this clearer.

In my opinion, something like `/path/to/mdn/content/files` is a fairly standard way of saying "replace this with your own path", but we coyld be clearer about that. I'd suggest replacing 

```
Make sure you point to the /files folder inside your clone of the content repo.
```

with something like

```
Make sure you replace /path/to/mdn/content/files in the above command with the path to the /files folder inside your clone of the content repo, on your own computer.
```

**Comment by mattiapontonio** [comment]
One of the underlying problems is that these commands cannot be copied and executed so _After that, run these commands in your bash:_ it is false, it should be 
_After that, read the paragraph after the following commands and then copy the following commands in a text area and then edit the following commands following the rules of the first paragraph after the commands and then run these commands in your bash:_

Sounds better?

**Comment by chrisdavidmills** [comment]
Well, all of the commands can be copied and executed except for the `echo...` line, and the `git clone...` line if you want to clone your own fork rather than the main repo.

You've helped me understand what is wrong with this now, so this was useful. I'll have a go at updating the text to make it better.

**Comment by mattiapontonio** [comment]
Thanks for doing it. Although the text is of value if there are solutions that do not make me struggle too much in reasoning and reading I prefer them.
Especially since the install command is also untrue. Ideally, software downloads, installs and runs. Configuration is a secondary thing for preferences.

**Comment by mattiapontonio** [comment]
I don't mean to be pretentious, you do what you can in open source of course.
👌

**Pull request closed without merging**
