### PR TITLE
open editor for translated content

### PR DESCRIPTION
**Pull request by fiji-flo**

### CODE REVIEW

**Review by peterbe — CHANGES_REQUESTED** [review]
Screen Shot 2021-03-11 at 1 05 43 PM

I don't know what in the code is wrong but it's not working in en-US docs.

**Comment by peterbe** [comment]
It's a bummer that we have no end-to-end tests for the "Open in your editor". 
I guess we could mock a binary that all it does is logging what it was opened with.

**Comment by peterbe** [comment]
By the way, it worked fine on http://localhost:3000/es/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions

**Comment by fiji-flo** [comment]
Weird. I'm sure I tested it and it should have never worked I guess 😕 

Good catch.

**Review by peterbe — APPROVED** [review]
works like a charm!

**Pull request merged**
