### PR TITLE
chore(macros/LearnSidebar): add Japanese translations for HTML and CSS

### PR DESCRIPTION
**Pull request by gurezo**
## Summary
@hmatrjp @potappo , mdn-yari-ja

please review for this pull request

- issue:  [サイドメニュー の翻訳(HTML — Structuring the web, CSS — Styling the web) #790](https://github.com/mozilla-japan/translation/issues/790) 

### Problem

- There is no Japanese translation yet

#### English pages

- cf. https://developer.mozilla.org/ja/docs/Learn/HTML
    - HTML — Structuring the web
        - Multimedia and embedding
        - HTML tables
- cf. https://developer.mozilla.org/ja/docs/Learn/CSS
    - CSS — Styling the web
        - CSS first steps
        - CSS building blocks
        - Styling text
        - CSS layout

#### Japanese pages

- cf. https://developer.mozilla.org/ja/docs/Learn/HTML
    - HTML — ウェブの構造化 
        - マルチメディアと埋め込み 
        - HTML 表 
- cf. https://developer.mozilla.org/ja/docs/Learn/CSS
    - CSS — ウェブのスタイル設定 
        - CSS の第一歩 
        - CSS の構成要素
        - テキストの装飾
        - CSSレイアウト 

|section|before| after |
|:----| :----: | :----:| 
| HTML | スクリーンショット 2024-09-21 13 49 01 | スクリーンショット 2024-09-21 14 20 40 |
| CSS | スクリーンショット 2024-09-21 13 55 26 | スクリーンショット 2024-09-21 14 09 52 |

### Solution

translate japanese for LearnSidebar.ejs

### NOTICE

@mdn/core-dev

Please merge once mdn-yari-ja is approved.

### Before

- There is no Japanese translation yet

### After

- tranlate japanese for LearnSidebar.ejs

### CODE REVIEW

**Comment by gurezo** [comment]
@hmatrjp @potappo , mdn-yari-ja

please review for this pull request

@mdn/core-dev

one question.
this PR was failed Compare bundle size / Build head (pull_request)

This action(Compare bundle size / Build head) was not included in the previous PR.
Please let me know how to fix this error.

I made two PRs(#11839, #11840) with the same results.

**Review by potappo — APPROVED** [review]
Thanks @gurezo , translation looks good.

**Review by IreneSAvila — APPROVED** [review]
9f11fbd61decd87291e60ede7772c5ba40a59fb5

**Comment by gurezo** [comment]
@IreneSAvila 
i had rebased main to my branch, and force push now.
 if it will be passed CI, Please review and merge.

**Review by IreneSAvila — APPROVED** [review]

**Comment by gurezo** [comment]
Hi @mdn/core-dev
this pr already arroved, when to merge?

**Review by caugner — APPROVED** [review]

**Pull request merged**
