### PR TITLE
avoid kumascript's string.toLower()

### PR DESCRIPTION
**Pull request by peterbe**
What do you think @ugultopu ?

### CODE REVIEW

**Comment by ugultopu** [comment]
Makes sense to me. I used `string.toLower` just because the macro was using `string.replace` instead of `$0.replace`. I thought there was some sort of coding practice that I didn't understand but should follow.

**Comment by peterbe** [comment]
> Makes sense to me. I used `string.toLower` just because the macro was using `string.replace` instead of `$0.replace`. I thought there was some sort of coding practice that I didn't understand but should follow.

You're absolutely right. Lets get rid of that too. 

Kumascript macros' JS code is old and weird.

**Comment by peterbe** [comment]
Now the weird `string.replace` is replaced too.

**Comment by ugultopu** [comment]
Looks great to me! Maybe even [kumascript/src/api/string.js] can be cleaned up or removed altogether after all references to the functions there have been replaced.

[kumascript/src/api/string.js]: https://github.com/mdn/yari/kumascript/src/api/string.js

**Review by escattone — APPROVED** [review]

**Pull request merged**
