### PR TITLE
JTS to TOC

### PR DESCRIPTION
**Pull request by mattiapontonio**
https://en.m.wikipedia.org/wiki/Table_of_contents

### CODE REVIEW

**Comment by peterbe** [comment]
I'm not convinced. It's in a side-bar after all. [GitHub Docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) calls it "In this article" which is nice. Accurate.

**Comment by mattiapontonio** [comment]
Even the cose uses `toc` and It has a Wikipedia article 🤷🏻‍♂️

**Comment by mattiapontonio** [comment]
I still want to call It 
**_Table_ of contents**

but i want to say that Is not a `table` but a `ul` 🤯

**Comment by peterbe** [comment]
"Table of contents" is usually something you have *in* the content. On the first page. Not on the side.

**Comment by mattiapontonio** [comment]
> A table of contents, usually headed simply Contents and abbreviated informally as TOC, is a list, usually found on a page _before the start of a written work_, of its chapter or section titles or brief descriptions with their commencing page numbers. 

- _document is a chapter_
- _origin is a book_

In general is the _content in the context_ like when you logs the `entries` in an _object_.

🌳

**Comment by mattiapontonio** [comment]
> I'm not convinced. It's in a side-bar after all. [GitHub Docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) calls it "In this article" which is nice. Accurate. 

## Table of contents in _this_ `article`

**Comment by mattiapontonio** [comment]
Side issue 

**mdn/content** provides _contents_ so It should be called mdn/contents.

**Comment by mattiapontonio** [comment]
Yes it could be moved but in separate PRs.
_I used to update in a commit and move in other commit._

**Comment by mattiapontonio** [comment]
```html
<article>
<section>
<h1>Table of contents</h1>
<table/>
</section>
<section/>
<section/>
</article>
```

**Comment by peterbe** [comment]
Let's not worry about making the change. But please feel free to start a discussion about changing the English. I don't think we should just jump into an edit without consent from the content folks.

**Pull request closed without merging**
