### PR TITLE
Preload zilla-slab font

### LINKED ISSUE #1502: Preload zilla-slab font
Even if we're going to inline the critical CSS, it actually makes sense to preload the most common font URLs that need to be downloaded (according to the CSS). 

[It's what we already do in Kuma](view-source:https://developer.mozilla.org/en-US/) and that's such an important "complaint" by our [Lighthouse score](https://github.com/mdn/yari/issues/1484) that it's worth investing in this ASAP.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #1502

**The problem with this is that it's not entirely obvious *which* font URL we should preload.**
In its current state, the only filtering I have is if there's a `.woff2` URL in the CSS. That leads to this:

```html
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-700italic.ffc7a913.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-700.aefbe7f1.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-600italic.cb82fcf8.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-600.861f6710.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-500italic.c8469aa2.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-500.52f6880f.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-400italic.0b291f4a.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-400.a4701e4e.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-300italic.c3e55b6e.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin="" href="/static/media/zilla-slab-latin-300.f39284f9.woff2">
```
And that's just nuts. 
Firefox will give you this warning if you do that:

Screen Shot 2020-10-20 at 2 56 36 PM

But I looked at how `@mdn/minimalist` works in the `mdn-fiori` branch and there there are only 2 URLs always. So perhaps this solution will be enough once we're in Fiori.

### CODE REVIEW

**Comment by peterbe** [comment]
@schalkneethling What I could do is make a new PR to go into `mdn-fiori` instead. But I'm not sure the code itself is inherently bad. It's just being a bit unfortunate now when we're still in `kumastyles`.

**Comment by schalkneethling** [comment]
> @schalkneethling What I could do is make a new PR to go into `mdn-fiori` instead. But I'm not sure the code itself is inherently bad. It's just being a bit unfortunate now when we're still in `kumastyles`.

I completely agree. The code is 💯  and will just work on the fiori side. This is great stuff, thanks @peterbe

**Comment by peterbe** [comment]
@schalkneethling Let's do this. Once, `mdn-fiori` is merged to master, we'll open this PR and you review it and we'll take it from there.

**Comment by peterbe** [comment]
Combine this with https://github.com/mdn/yari/pull/1499 and when these two are merged and in `master` I'll do one last check of the Lighthouse score and if it's OK, I'll close https://github.com/mdn/yari/issues/1484

CC @escattone

**Comment by escattone** [comment]
Nice thanks @peterbe!

**Review by schalkneethling — APPROVED** [review]
🦖

**Pull request merged**
