### PR TITLE
Anchor links casing should always be corrected in build-time

### LINKED ISSUE #2763: Anchor links casing should always be corrected in build-time
Oh no. It's either a regression or it's a matter of some code that hasn't landed yet :(

But if the raw HTML is this:
```html
<a href="#Specifying_a_function_as_a_parameter">Specifying a function as a parameter</a>
```

it *should* become...

```html
<a href="#specifying_a_function_as_a_parameter">Specifying a function as a parameter</a>
```

...when it gets rendered out. 
I'll take care of looking into this on the Yari side.

_Originally posted by @peterbe in https://github.com/mdn/content/issues/1854#issuecomment-771039881_

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #2763

### CODE REVIEW

**Comment by peterbe** [comment]
Hey @kauer3  can you help review this? Basically, what I did was:

In one terminal...
```
yarn dev
```
In another terminal...
```
BUILD_FLAW_LEVELS="*:ignore" BUILD_FOLDERSEARCH=web/javascript/reference/global_objects/string/replace yarn build
```

^ this kinda what the production builder does (except no foldersearch filtering).

**Comment by kauer3** [comment]
@peterbe I'll be very happy to, but I may need some help, never did this before.

**Review by escattone — COMMENTED** [review]
@peterbe Thanks for the examples to check! So this is an interesting change in that we're automatically applying suggested fixes for broken-link flaws during the build for the first time, right? I've lost my feel for some of the details wth flaws, so you may have to educate me tomorrow, but I'm concerned that we're now automatically fixing flaws as a side effect of `injectFlaws`, i.e. outside of the `fixFixableFlaws` function. I may be missing something though.
I tested it on the examples you provided and it worked great.

**Comment by peterbe** [comment]
It's right. Basically fixing fixable flaws, at build-time, up until actually adding the flaw to the doc and updating the index.html source file. 

If this makes us nervous, we can opt to just lower-casing anchor links. 

But it's also pretty neat in that it means all anchor links will immediately work and users won't have to go through redirects unnecessarily when they click links.

**Comment by peterbe** [comment]
I'm going to check what impact this has on the build rate.

**Comment by peterbe** [comment]
I ran a build again. The total build time was not affected by this extra cheerio checking stuff. 

The only thing I don't like about this PR is that things are now named a bit oddly. It's called `injectFlaws()` but, instead, what it does is that it mutates the `$` object that's passed in. Gregor and I had a this debate too and we didn't get very far. We concluded and agreed that it's poorly named and that we should rearrange and rename things so it's less surprising to an untrained eye. But no great progress on that (re)naming work yet.

**Comment by peterbe** [comment]
I don't think the poor naming should block. For now. But please spend a little time sharing what you think would be a more appropriate layout of the functions and their names to make it *feel* more natural and predictable.

**Review by escattone — APPROVED** [review]
@peterbe It may be that the flaw code/system needs some refactoring after everything that's gone into it, but that shouldn't hold this up.

**Pull request merged**
