### PR TITLE
Remove Navigator* mixins from sidebar

### PR DESCRIPTION
**Pull request by teoli2003**
This is the companion PR of mdn/content#6637, cleaning the relevant sidebars.

### CODE REVIEW

**Comment by teoli2003** [comment]
Ok, it looks like the original failure, was a transient one.

**Comment by peterbe** [comment]
@teoli2003 Do you have the permission to request a review on this PR? If so can you pick whoever reviewed https://github.com/mdn/content/pull/6637

But quick blurb here; if we invest in https://github.com/mdn/yari/pull/4081 you'd be able to combine your content changes with the updates to these `.json` files.

**Comment by teoli2003** [comment]
Thanks! No I don't have the rights.

But, no worry here: once the content and bcd companion PRs are approved (They are the complex part of this cleaning), I'll ping the needed reviewers. I also alway link the GroupData PR in the mdn PR so it doesn't get forgotten (same for the bcd PR).

I noticed #4081 and I agree it would be cool! We are cleaning a lot these days and it will make things easier.

**Comment by teoli2003** [comment]
The two companions PR have landed and sticked.

@Elchi3, can you review this (and hopefully approve)?

**Review by Elchi3 — APPROVED** [review]

**Pull request merged**
