### PR TITLE
fix: fix the translation of `Responsive_design`

### PR DESCRIPTION
**Pull request by liulinboyi**
Fix the translation of `Responsive_design`

### CODE REVIEW

**Review by yin1999 — APPROVED** [review]
LGTM for `zh-CN`

**Comment by yin1999** [comment]
cc @mdn/core-yari-dev

**Comment by schalkneethling** [comment]
Thank you for your pull request @liulinboyi and welcome to the community 🎉

**Comment by schalkneethling** [comment]
@yin1999 thank you for bringing our attention to the pull request and reviewing. For pull request such as these, feel free to ping @mdn/mdn-community-engagement - Thank you!

**Comment by schalkneethling** [comment]
Hey @liulinboyi, this repository requires [signed commits](https://docs.github.com/articles/about-gpg/). No worries for this pull request but, for future pull request we will not be able to merge unless the commits are signed. Thank you for understanding.

**Review by schalkneethling — APPROVED** [review]
Congratulations on your first merged pull request 🎉 While we are making it easier for new contributors to find ways to contribute, please let us know what areas you are interested in contributing to. Also, we have a Matrix channel(https://matrix.to/#/#mdn:mozilla.org) you can join in speaking with the MDN team and other community members.

**Comment by yin1999** [comment]
> @yin1999 thank you for bringing our attention to the pull request and reviewing. For pull request such as these, feel free to ping @mdn/mdn-community-engagement - Thank you!

Thanks for mention this

**Pull request merged**
