### PR TITLE
chore(server): remove dev middlewares + merge start:{dev-server,server} scripts

### PR DESCRIPTION
**Pull request by OnkarRuikar**
(Original description below)

## Summary

Cleans up the `server`.

### Problem

We added dev middlewares in https://github.com/mdn/yari/pull/5664 that were actually only loaded under specific circumstances (if `NODE_ENV` was explicitly set to `"development"`), and this was not necessary to achieve hot module reloading.

### Solution

Remove the dev middlewares and merge the `start:dev-server` and `start:server` scripts.

---

## How did you test this change?

Tried both `yarn dev` and `yarn start` separately, verifying that changes to `index.tsx` and/or `index.scss` are hot-reloaded on http://localhost:3000/.

---

(Original description as follows:)

## Summary

Getting a typeerror during `yarn dev`:

```
7:20:48 AM web.1        |  Starting the development server...
7:20:48 AM server.1     |  TypeError: Cannot read properties of undefined (reading 'publicPath')
7:20:48 AM server.1     |      at file:///mdn/yari/server/dev.ts:29:40
7:20:48 AM server.1     |  [ERROR] 21:50:48 TypeError: Cannot read properties of undefined (reading 'publicPath')
```

### After

```
7:24:16 AM web.1        |  Starting the development server...
7:24:18 AM server.1     |  [HPM] Proxy created: /  -> http://localhost:8080
7:24:18 AM server.1     |  [HPM] Proxy created: /  -> https://developer.mozilla.org
7:24:18 AM server.1     |  [HPM] Proxy created: /  -> https://developer.allizom.org
```

## How did you test this change?

`yarn dev` before and after fix

### CODE REVIEW

**Comment by caugner** [comment]
@OnkarRuikar Are you still experiencing this issue? I cannot reproduce it locally, so I'm wondering whether your `node_modules` folder might just be corrupt? But then again I guess you've already tried `rm -rf node_modules && yarn`.

**Comment by caugner** [comment]
> file:///home/onkar/GitHub/mdn/yari/server/dev.ts:29:40

@OnkarRuikar Are you on Windows?

**Comment by caugner** [comment]
It seems that you have `NODE_ENV = "development"` in your environment (or `.env` file), and that I missed in https://github.com/mdn/yari/pull/5664 to assume that `NODE_ENV` is "development" unless specified otherwise.

**Comment by caugner** [comment]
@OnkarRuikar Sorry for "taking over" this PR, but one change lead to another. 😉 

Would you mind checking out my changes? It seems that the dev middlewares weren't necessary, after all.

**Review by queengooborg — APPROVED** [review]
Confirming that everything's working as expected, both with `NODE_ENV` set to `development` and unset -- LGTM!

**Comment by OnkarRuikar** [comment]
> @OnkarRuikar Sorry for "taking over" this PR

Please do take over when needed. Thanks for fixing this quickly!\
In my environment after deleting `node_module` and `yarn install` it works with and without `development` set. I haven't tested hot loading in both.

> but one change lead to another. :wink:

You nerd sniped yourself! :smiley: 

***
> $ ts-node tool/cli.ts spas
> error running rg: undefined: No such file or directory (os error 2)

The error is because `BLOG_ROOT` is not set in `.env` file. :facepalm: The repo is not public...\
The current error message is not helpful at all. I spent time looking into the PATH and environment variables. Sending a PR to avoid the error and for logging better error messages.

**Pull request merged**
