### PR TITLE
Fix og:image for dark backgrounds

### PR DESCRIPTION
**Pull request by KartikSoneji**
The `og:image` has a transparent background, which makes it difficult to see on dark colors.

Twitter in dark mode:
image

Replacing the transparent pixels with white should fix it:
```console
$ convert mdn-social-share.png -background white -alpha remove mdn-social-share.png
```
image

### CODE REVIEW

**Comment by peterbe** [comment]
Much apprecated. This'll definitely help all those times it's shared via Slack too :)
Screen Shot 2021-06-14 at 5 56 55 AM

But before we merge this, would you mind running it through https://squoosh.app/ or some other program that can optimize it a bit. I ran it through Optimage on my mac and it saved 43%. 

If you don't have time, that's OK too. We can take care of that.

**Comment by schalkneethling** [comment]
Thanks you @KartikSoneji! As Peter mentioned, if you have a moment, running it through an image compression utility would be great but not a blocker. Let us know, thanks!

**Comment by schalkneethling** [comment]
Also, we require all commits to be signed, please see more information on this here:
https://docs.github.com/articles/about-gpg/

**Comment by KartikSoneji** [comment]
> would you mind running it through https://squoosh.app/ or some other program that can optimize it a bit

Done.

**Comment by KartikSoneji** [comment]
> Also, we require all commits to be signed, please see more information on this here:
> https://docs.github.com/articles/about-gpg/

Sorry, I still have everything setup from last time, just forgot to add `-S` while committing.

**Review by schalkneethling — APPROVED** [review]

**Comment by schalkneethling** [comment]
@peterbe you happy with this one?

**Review by peterbe — APPROVED** [review]

**Comment by peterbe** [comment]
THANK YOU @KartikSoneji 
We have had this on our to-do list for a while but there's a lot going on. Reviewing your PR was a joy. Please see if there are more things like this you can help out with. Love it!

**Pull request merged**
