### PR TITLE
enhance(build): improve expected document path error message

### PR DESCRIPTION
**Pull request by PassionPenguin**
## Summary

hopefully fixes #11531

### Problem

the thrown error message of build script is not obvious enough.

### Solution

added the expected path to the very end of the error message

### CODE REVIEW

**Comment by caugner** [comment]
@PassionPenguin Can you please check the referenced issue? https://github.com/mdn/yari/pull/11531 is a PR, not an issue. 😕

**Comment by PassionPenguin** [comment]
> @PassionPenguin Can you please check the referenced issue? #11531 is a PR, not an issue. 😕

sorry...that's #10277 (https://github.com/mdn/yari/issues/10277)
image

**Comment by PassionPenguin** [comment]
> > @PassionPenguin Can you please check the referenced issue? #11531 is a PR, not an issue. 😕
> 
> 
> 
> sorry...that's #10277 (https://github.com/mdn/yari/issues/10277)
> 
> image
> 
> 

Hi @caugner! I found this PR has been opened for 2mo without further request or question? Would you like to have a review on this?

**Comment by argl** [comment]
@LeoMcA The PR looks good to me, could you have a quick look at why the bundle size action fails?

**Comment by skyclouds2001** [comment]
it seems to failed with https://github.com/mdn/yari/pull/11831 for the same reason

**Review by argl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
