### PR TITLE
disable auto-complete search in non-CRUD mode

### PR DESCRIPTION
**Pull request by peterbe**
Part of #1663

Over to you @schalkneethling !
To review this, start two terminals:

1. `yarn start:static-server`
2. `yarn prepare-build && BUILD_FOLDERSEARCH=web/html/element/v yarn build`

Now you can go to http://localhost:5000/en-US/docs/Web/HTML/Element/video/ and see it in action. 
If that's too cumbersome you can inject a temporary hack in `ui/molecules/search/index.tsx` and replace the `CRUD_MODE` with just `false` and now you can use http://localhost:3000/en-US/docs/Web/HTML/Element/video/ and you get hot-reloading as you're editing and its SCSS.

The goal is that the search widget looks like that on https://developer.mozilla.org/en-US/ 
How we solve the styling is up to you. Perhaps you want to hack Kuma a bit or you can inject some hacks. 
I'm personally not that bothered about the little magnifying glass icon. But it would be nice if both have rounded corners or both don't have rounded corners.

### CODE REVIEW

**Comment by peterbe** [comment]
Also, when you hit Enter it won't work. But that's fine. It'll work on Stage where `/en-US/search?q=...` is taken over by Kuma.

**Comment by peterbe** [comment]
One caveat is that all the fancy new Yari search widget's code is still part of the main JS bundle, but never used. So it makes the JS bundle bigger than necessary. But this is a compromise. It should encourage us to hurry up and build the home page and site-seach in Yari instead of Kuma. Also, by doing it like this, writers who run `yarn start` on `mdn/content` can use the new search widget. 
Perhaps it might be a good idea to use lazy-loading instead. We could wrap up all the new search widget as a lazy-loaded module that is contingent on `CRUD_MODE`. 
What do you think?

**Comment by peterbe** [comment]
Hmm... Of course the tests are going to fail now :(
Need to think up a solution. I still think you can proceed with reviewing @schalkneethling

**Comment by peterbe** [comment]
Actually, whilst you review, I'm going to see if it's easy and or possible to move the auto-complete search into a code-splitted thing.

**Comment by peterbe** [comment]
@schalkneethling There's a problem still. 
When you follow the PR description steps to reproduce, you'll end up with 
```html
<form action="/en-US/search">
<label for="main-q" class="visually-hidden">Search MDN</label>
<input type="search" name="q" id="main-q" class="search-input-field" placeholder="Search MDN" pattern="(.|\s)*\S(.|\s)*" required="">
</form>
```
but there's a problem. I copied this DOM from Kuma. 
When you click into the input field but then decide to NOT type something so you click outside to blur the input, then this happens:
Screen Shot 2020-11-13 at 2 43 42 PM

Any ideas how Kuma solved that?

**Comment by peterbe** [comment]
@schalkneethling This one can wait till last minute, in a sense, but let's not forget it because it's critical to the launch on Dec 14.

**Review by schalkneethling — APPROVED** [review]
Works as advertised :) Thank you Peter.

**Pull request merged**
