### PR TITLE
moved a data to a data-attribute

### PR DESCRIPTION
**Pull request by mattiapontonio**
.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
What have you done to test this? This would needs other code to be changed, right? Why there no other code touched on this patch?

**Comment by mattiapontonio** [comment]
- I didn't test it in terms of cloning and launch the local environments.
- I don't have the draft functionality when I open the PR from mobile like in that case. I saw the thing and I drafted a PR...

**Comment by mattiapontonio** [comment]
https://github.com/search?q=org%3Amdn+bc-browser-&type=code

**Comment by mattiapontonio** [comment]
Since in Yari i found only 2 results that should be not connected since they are both in HTML / Jsx i Mark this PR as ready for review.

**Comment by mattiapontonio** [comment]
I Will retry, maybe.

**Pull request closed without merging**
