### PR TITLE
chore: Push down downshift to devDependency

### PR DESCRIPTION
**Pull request by nschonni**
Used by search.tsx, and the other client deps appear to be
devDependencies currently

Addresses `yarn install` warning on the mdn/content repo
```
warning "@mdn/yari > downshift@6.0.10" has unmet peer dependency "react@>=16.8.0".
```

### CODE REVIEW

**Comment by peterbe** [comment]
No can do. We use `downshift` for the autocomplete search widget, which you see when you start `http://localhost:5000`.
It's sad that we don't have any CI that simulates running yari from the npm package you'd get from `npm pack` :(

**Comment by peterbe** [comment]
By the way, what does "
```
warning "@mdn/yari > downshift@6.0.10" has unmet peer dependency "react@>=16.8.0".
```
even mean?

**Comment by nschonni** [comment]
Yes, it's referenced in 
https://github.com/mdn/yari/blob/2a009529b4d7fa35d3cff96c43aea067a3d2a26a/client/src/search.tsx#L1-L5

But `react` and `react-router-dom` are devDependencies currently. Either they should be hoisted if you're saying the files under the `client` folder should be working outside this repo, or `downshift` and the other react related dependencies should be demoted till you decide that you're going live with the react/ssr stuff

**Comment by peterbe** [comment]
Ahha! You are so very right!
Now my post-vacation brain is slowly kicking into gear. Yeah, we compile all those things like `react`, `react-router`, `downshift`, etc. into bundle ES5 `.js` files.

**Comment by peterbe** [comment]
I'm sorry for the hasty conclusion. 
Would you mind merging in `master` and we'll try again?

**Review by peterbe — APPROVED** [review]

**Comment by nschonni** [comment]
@peterbe oddly got a timeout on the search in the first rebase, hoping the second one goes back to green again 😆

**Comment by peterbe** [comment]
The tests that failed do depend on `downshift`. Hmm.
Also, please refrain from using rebase if you can. Especially squashing.

**Comment by nschonni** [comment]
> Also, please refrain from using rebase if you can. Especially squashing.

It's the best way to resolve merge conflicts. Also if you've marked the files as "reviewed", GitHub can already tell if files are changed and marks them as "Changed since last review" for you

**Comment by peterbe** [comment]
> It's the best way to resolve merge conflicts.

How so? I use: `git merge master` and if there are merge conflicts, I have to manually open VSCode and fix it (unless it's `yarn.lock`). When I'm done I type `git commit -a -m "master merged in"`. 
I don't think it's any different merge conflicts if you use rebase. 

The disadvantage with rebase is that anybody who has pulled your branch can't pull again. 

Also, something I've never fully understood is that if you've resolved conflicts once with rebase, for some reason you might have to do it again if you rebase and encounter new merge conflicts. Perhaps that's old git from before the days I stopped using it. 

PS. Sometimes I do use `git rebase -i master` when I want to delete some embarrassing commit that might have some offensive commit message.

**Comment by peterbe** [comment]
Oh I see. Not only did you move it, you also upgraded it. That might explain why the tests are failing. 
Perhaps we can tackle that first and separately once Dependabot initiates that upgrade. Once that's in, we can just move it from `dependencies` to `devDependicies` without touching the `yarn.lock`.

**Comment by nschonni** [comment]
yeah, I'll see if I can pin the version with I Yarn remove/add -D

**Comment by peterbe** [comment]
No, I suggest we close this or hold off on this. You're going to get CI failures anyway. I suspect Dependabot will attempt to upgrade within a day or so.

**Comment by nschonni** [comment]
> Also, something I've never fully understood is that if you've resolved conflicts once with rebase, for some reason you might have to do it again if you rebase and encounter new merge conflicts. Perhaps that's old git from before the days I stopped using it.

I generally run `git rum` from my aliases here https://github.com/nschonni/dotfiles/blob/master/.gitconfig#L11 for conflicts and resolve in VS Code as well

**Comment by nschonni** [comment]
@peterb it seems happy now with 6.014 that reverted the change in 6.0.12

**Comment by peterb** [comment]
@nschonni did you mean @peterbe?

**Comment by peterbe** [comment]
> @nschonni did you mean @peterbe?

I bet he most certainly did :)
Hi by the way! Nice name you've got!

**Review by peterbe — APPROVED** [review]
Have you tested it? Like on http://localhost:3000 
Or did you just worry about the CI passing?
(...which, in theory, should be good enough or our end-to-end tests are lacking)

**Comment by nschonni** [comment]
> Or did you just worry about the CI passing?

Just the CI, since it does the prod install

**Review by peterbe — APPROVED** [review]

**Pull request merged**
