### PR TITLE
security(api): add csrf

### PR DESCRIPTION
**Pull request by ElijahPepe**
## Summary
This PR adds [CSRF](https://developer.mozilla.org/en-US/docs/Glossary/CSRF) via middleware using the [`csurf`](https://www.npmjs.com/package/csurf) package.

### Problem
An attacker can utilize CSRF to enact unwanted changes on a user's account.

### Solution
This PR adds in middleware that prevents CSRF attacks.

---

## How did you test this change?
I tested this change via manual testing.

### CODE REVIEW

**Comment by caugner** [comment]
@ElijahPepe Can you elaborate which API calls or requests were missing the CSRF token?

**Comment by ElijahPepe** [comment]
From a quick glance, I believe all of the calls were missing a proper CSRF token.

**Comment by ElijahPepe** [comment]
I wasn't aware that the plus notification calls include a CSRF token. Looking at it now, I can see that the paths for signing out and MDN Plus notifications do have CSRF tokens. The endpoints for everything else, like `/api/v1/whoami` or `/users/fxa/login/authenticate` do not utilize CSRF.

**Comment by caugner** [comment]
> The endpoints for everything else, like `/api/v1/whoami` or `/users/fxa/login/authenticate` do not utilize CSRF.

Thanks for looking into it. I don't really see a security problem with those endpoints though, since they're GET routes and don't allow any modifications (see https://security.stackexchange.com/a/115810). Maybe I'm missing something?

Note also that the static server you're modifying is only used during development. Our production environment is just static files, with `/api/v1/whoami` and `/users/fxa` being mapped to [kuma](https://github.com/mdn/kuma).

**Comment by ElijahPepe** [comment]
After looking at the POST endpoints used in this repository again, seems like CSRF is already implemented. I'll close this for now.

**Comment by caugner** [comment]
Thanks for watching out for potential security issues like this, @ElijahPepe! 🎉

**Pull request closed without merging**
