### PR TITLE
fetch all a href then assign data status

### PR DESCRIPTION
**Pull request by mattiapontonio**
#2289

### CODE REVIEW

**Comment by mattiapontonio** [comment]
I Will take a pause after passing from 3 fails to 2 fails ⏸️🛌

**Comment by mattiapontonio** [comment]
I Will Mark this to ready for review for help

**Comment by peterbe** [comment]
@mattiapontonio This PR is completely out of context and doesn't address any described problem. It won't be reviewed or merged. So please don't spend too much time on it.

**Comment by mattiapontonio** [comment]
@peterbe Is _half-ok_.
I can't understand the action...

**Comment by mattiapontonio** [comment]
For the record here Is ready to merge 🤷🏻‍♂️

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/2065#issuecomment-761105203

**Pull request closed without merging**
