### PR TITLE
fix(plus/docs): add screenshots

### PR DESCRIPTION
**Pull request by schalkneethling**
Adds screenshots to the Plus feature documentation

Fix https://github.com/mdn/foxfooding-mdn-plus/issues/54

### CODE REVIEW

**Comment by schalkneethling** [comment]
Ignore for now. Will address conflicts.

**Comment by schalkneethling** [comment]
> Did you see them locally? If so, what command(s) did you run?

That is odd. I saw them locally and on stage 🤔

**Comment by schalkneethling** [comment]
The screenshot below is from staging.

Screenshot 2022-03-25 at 19 34 54

Locally I just ran `yarn dev`

**Comment by schalkneethling** [comment]
Another one from staging:

Screenshot 2022-03-25 at 19 36 06

**Comment by caugner** [comment]
@schalkneethling It turns out that I had MDN Offline enabled locally, and that's why I got old versions of the MDN Plus Docs. 🤦

**Review by caugner — APPROVED** [review]

**Comment by schalkneethling** [comment]
> @schalkneethling It turns out that I had MDN Offline enabled locally, and that's why I got old versions of the MDN Plus Docs. 🤦

After a week like this, there is no reason to feel bad 😸

**Pull request merged**
