### PR TITLE
Update pegjs docs link

### PR DESCRIPTION
**Pull request by shapkarin**
pegjs docs are at https://pegjs.org/documentation

### CODE REVIEW

**Review by escattone — APPROVED** [review]
Thanks @shapkarin

**Comment by escattone** [comment]
Oops, forgot to say that we require that you sign your commits. See https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits.

**Comment by shapkarin** [comment]
@escattone will sign

**Comment by shapkarin** [comment]
signed Screenshot 2021-08-11 at 02 25 37

**Pull request merged**
