### PR TITLE
fix: update mdn web docs logo

### LINKED ISSUE #1961: menu cuts the logo

### LINKED ISSUE #2094: change logo to "MDN Web Docs"
On https://developer.mozilla.org/en-US/
In the document title:
Screen Shot 2020-12-11 at 3 27 27 PM

In the logo:
Screen Shot 2020-12-11 at 3 28 08 PM

On https://developer.mozilla.org/en-US/docs/MDN
Screen Shot 2020-12-11 at 3 28 39 PM

### PR DESCRIPTION
**Pull request by schalkneethling**
Update MDN Web Docs logo to use agreed-upon case style.

Screenshot 2020-12-14 at 14 05 13

fix #2094
fix #1961

### CODE REVIEW

**Review by peterbe — CHANGES_REQUESTED** [review]
@ddbeck was faster at spotting it 
https://github.com/mdn/yari/issues/2094#issuecomment-744456187

**Comment by peterbe** [comment]
Just so I don't forget, we should take this opportunity to fix it so that the footer logo uses the same SVG component. The repetition is bad for the HTML size but since it's repeated it'll compress very well.

**Comment by peterbe** [comment]
I don't know if this has been updated yet, but the logo is missing in the footer. 
Screen Shot 2020-12-15 at 2 17 48 PM

**Comment by schalkneethling** [comment]
> I don't know if this has been updated yet, but the logo is missing in the footer.

:( Made a silly mistake.

**Comment by schalkneethling** [comment]
@peterbe Apologies for the hiccup. Resolved now.

**Review by peterbe — APPROVED** [review]
Awesome!!!

**Pull request merged**
