### PR TITLE
chore(deps): bump @webref/css from 6.0.0 to 6.7.1

### LINKED ISSUE #10004: Preview wrong
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/order

### What specific section or headline is this issue about?

Formal syntax

### What information was incorrect, unhelpful, or incomplete?

Compare the "Formal syntax" sections at  https://developer.mozilla.org/en-US/docs/Web/CSS/order vs https://pr30158.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/order

### What did you expect to see?

Matching

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/order`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/order
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/order/index.md
* Last commit: https://github.com/mdn/content/commit/fab1f9cef824066b3ce6a5b25f6c6db539f5d042
* Document last modified: 2023-07-18T00:07:20.000Z

</details>

### PR DESCRIPTION
**Pull request by caugner**
## Summary

Fixes https://github.com/mdn/yari/issues/10004.

### Problem

We recently upgraded to `@webref/css` v6, but Dependabot didn't upgrade to the latest minor/patch version yet.

### Solution

Upgade manually.

---

## How did you test this change?

TBD

### CODE REVIEW

**Review by caugner — COMMENTED** [review]
Here's why this isn't merged yet:

| 6.0.0 | 6.7.1 |
|--------|--------|
| image | image |

**Comment by OnkarRuikar** [comment]
> Here's why this isn't merged yet:

What's wrong? Here `<url>` is a type and `<url()>` is a function.
With the latest version it is reflected accurately `<url>=<url()>|<src()>` as per [the latest spec](https://drafts.csswg.org/css-values-4/#urls).

**Comment by caugner** [comment]
> What's wrong? Here `<url>` is a type and `<url()>` is a function.
> With the latest version it is reflected accurately `<url>=<url()>|<src()>` as per [the latest spec](https://drafts.csswg.org/css-values-4/#urls).

Oh, you're right, apparently I didn't look closely enough.

**Review by caugner — COMMENTED** [review]
Self-approval, because it's "just" a minor dependency update.

**Pull request merged**
