### PR TITLE
Update OWD info on community page

### PR DESCRIPTION
**Pull request by Elchi3**
## Summary

Update OWD info on the community page http://localhost:3000/en-US/community

### Problem

Community page contains outdated info about OWD.

### Solution

Update to current info.

## How did you test this change?

Locally. 
Basically this is the same PR as last year: https://github.com/mdn/yari/pull/8619

### CODE REVIEW

**Comment by Elchi3** [comment]
What can I do to move this PR forward?

**Review by estelle — APPROVED** [review]

**Comment by LeoMcA** [comment]
Thanks, but this page is pretty outdated overall and we're working on reviewing/updating this page wholesale, along with our other noncontent pages, which should be done in Q3. Closing for now

**Comment by estelle** [comment]
> Thanks, but this page is pretty outdated overall 

This PR helps resolve your concerns by making the content on the page less outdated. Keeping outdated information on MDN for an additional three months instead of merging a PR that resolves at least part of the issue seems nonsensical. 

Does this mean there is a hold on all Yari content and all maintainers and volunteer contributors should file issues instead of PRs until the new design and content developed during Q3 is released in Q4?

**Comment by meyerweb** [comment]
I'm bothered by the incorrect information persisting for a number of months when it could be very easily fixed here.  It may be small, but these sorts of things can add up to making MDN look like it's losing relevance, which isn't something I think we want.

**Pull request closed without merging**
