### PR TITLE
add tool command for rendering/removing macros

### PR DESCRIPTION
**Pull request by escattone**
Adds a new `yarn tool macros` command to either `render` or `remove` one or more macros from a tree of documents.

### CODE REVIEW

**Comment by escattone** [comment]
Here are some examples:

### Rendering-out `cssxref` macro (skipping when un-fixable flaws)
```sh
rjohnson-44864:yari rjohnson$(maws_profile)$ yarn tool macros render en-us/web/css/transform cssxref
yarn run v1.22.5
$ node tool/cli.js macros render en-us/web/css/transform cssxref
render the macro(s) "cssxref" within content folder(s) matching "en-us/web/css/transform"
/Users/rjohnson/repos/content/files/en-us/web/css/transform-box/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/matrix()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/matrix3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/perspective()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotate()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotate3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotatex()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotatey()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotatez()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scale()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scale3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scalex()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scaley()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scalez()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/skew()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/skewx()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/skewy()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translate()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translate3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translatex/index.html:
  skipping, has 1 non-fixable flaw(s) (MacroBrokenLinkError)
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translatey()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translatez()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-origin/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-style/index.html:
  no change
/Users/rjohnson/repos/content/files/en-us/web/css/transform/index.html:
  fixing 1 fixable flaw(s) before proceeding:
    {{cssxref("transform-function/perspective", "perspective()")}} --> {{cssxref("transform-function/perspective()", "perspective()")}}
  modified
modified: 24 | no-change: 1 | skipped: 1 | total: 26
✨  Done in 8.91s.
```

### Rendering-out `cssxref` macro (forcing render when un-fixable flaws)
```sh
rjohnson-44864:yari rjohnson$(maws_profile)$ yarn tool macros render en-us/web/css/transform cssxref -f
yarn run v1.22.5
$ node tool/cli.js macros render en-us/web/css/transform cssxref -f
render the macro(s) "cssxref" within content folder(s) matching "en-us/web/css/transform"
/Users/rjohnson/repos/content/files/en-us/web/css/transform-box/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/matrix()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/matrix3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/perspective()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotate()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotate3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotatex()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotatey()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/rotatez()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scale()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scale3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scalex()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scaley()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/scalez()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/skew()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/skewx()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/skewy()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translate()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translate3d()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translatex/index.html:
  ignoring 1 non-fixable flaw(s) (MacroBrokenLinkError)
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translatey()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-function/translatez()/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-origin/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/web/css/transform-style/index.html:
  no change
/Users/rjohnson/repos/content/files/en-us/web/css/transform/index.html:
  fixing 1 fixable flaw(s) before proceeding:
    {{cssxref("transform-function/perspective", "perspective()")}} --> {{cssxref("transform-function/perspective()", "perspective()")}}
  modified
modified: 25 | no-change: 1 | skipped: 0 | total: 26
✨  Done in 8.94s.
```

### Removing `fx_minversion_header` macro
```sh
rjohnson-44864:yari rjohnson$(maws_profile)$ yarn tool macros remove en-us/mozilla fx_minversion_header
...
/Users/rjohnson/repos/content/files/en-us/mozilla/thunderbird/autoconfiguration/fileformat/definition/index.html:
  no change
/Users/rjohnson/repos/content/files/en-us/mozilla/thunderbird/autoconfiguration/fileformat/howto/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/mozilla/thunderbird/autoconfiguration/fileformat/index.html:
  no change
/Users/rjohnson/repos/content/files/en-us/mozilla/thunderbird/autoconfiguration/index.html:
  modified
/Users/rjohnson/repos/content/files/en-us/mozilla/virtualenv/index.html:
  modified
modified: 560 | no-change: 739 | skipped: 0 | total: 1299
✨  Done in 13.63s.
```

**Comment by Elchi3** [comment]
I'm very excited about this PR, Ryan! 🚀

**Review by fiji-flo — COMMENTED** [review]
Looks good. I'd suggest we move most of the logic from `tool` to `content` to make it easier to reuse.

**Comment by peterbe** [comment]
@escattone and I chatted about this. Some more thoughts needs to go into whether we make this part of the "core Yari API" (e.g. moving it into the `content` directory). Or, perhaps we treat it as a hacky script that we use for a couple of weeks and then throw away.

**Comment by escattone** [comment]
@fiji-flo Are you OK with landing this as is (so we can start using it for our Q1 goals), and refactoring later when we find a use case for reusing it?

**Comment by fiji-flo** [comment]
@escattone sure

**Comment by fiji-flo** [comment]
Just to be aware of: it'll apply some implicit formatting via `cheerio` like converting a ` ` (that's a `\u{a0}`) into `&nbsp;` and changes line breaks.

Nothing to worry about but the _modified_ might be misleading.

**Pull request merged**
