### PR TITLE
Update the translation of zh-CN

### PR DESCRIPTION
**Pull request by isunjn**
Part of sidebar title still remain en-US, I fix that.

### CODE REVIEW

**Comment by peterbe** [comment]
Can someone from the zh team please review this?
@mdn/yari-content-zh

**Comment by peterbe** [comment]
Just in case mentioning `@mdn/yari-content-zh` doesn't notify individuals, can you take a look @irvin

**Comment by peterbe** [comment]
I'm actually working on a new sidebar implementation that will draw the titles for the links from the documents themselves. But there are some times when you might want to override that.

**Comment by isunjn** [comment]
> I'm actually working on a new sidebar implementation that will draw the titles for the links from the documents themselves. But there are some times when you might want to override that.

This can be a better way for sidebar, how long will it take?

**Comment by irvin** [comment]
I think this is all good.

**Comment by peterbe** [comment]
> > I'm actually working on a new sidebar implementation that will draw the titles for the links from the documents themselves. But there are some times when you might want to override that.
> 
> This can be a better way for sidebar, how long will it take?

The code is actually finished but I haven't tested it yet.

**Pull request merged**
