### PR TITLE
chore(macros/AddonSidebar): add Background scripts page

### PR DESCRIPTION
**Pull request by rebloor**
## Summary
Add the new Background scripts page to the web extensions sidebar menu. see  https://github.com/mdn/content/pull/15533

### CODE REVIEW

**Comment by caugner** [comment]
> ** do not merge until all manifest V3 content is ready **

@rebloor Please [convert the PR to draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) to signal this.

**Comment by rebloor** [comment]
@caugner However, this is ready for review just not ready to be merged

**Review by caugner — COMMENTED** [review]
LGMT

**Review by caugner — COMMENTED** [review]
LGTM, but it doesn't look like the page has landed in mdn/content yet.

**Comment by rebloor** [comment]
@caugner the page is now landed, thanks

**Review by caugner — APPROVED** [review]

**Pull request merged**
