### PR TITLE
chore(pong): update mapping

### PR DESCRIPTION
**Pull request by fiji-flo**
## Summary

Just adjusting API changes.
Incorporating alt in a follow up.

### CODE REVIEW

**Review by caugner — COMMENTED** [review]
How can I test this?

**Comment by fiji-flo** [comment]
It's on stage.

**Review by caugner — APPROVED** [review]
Ads look good on stage, so LGTM.

PS: I didn't see alt texts though, but I assume they're not configured for the ads I saw.

**Review by caugner — COMMENTED** [review]
(deleted)

**Review by caugner — APPROVED** [review]
LGTM, I can see ads with alt texts on stage.

Note: I didn't see any top banner, so I wasn't able to verify that the CTA text shows up.

**Pull request merged**
