### PR TITLE
refactor(build): split up document-extractor

### PR DESCRIPTION
**Pull request by caugner**
## Summary

Splits up the `build/document-extractor.ts` into individual files.

### Problem

The `document-extractor` has 833 lines and extracts multiple things that don't need to be together.

### Solution

Split it up into multiple `extract-*` files.

---

## Screenshots

n/a

---

## How did you test this change?

Not yet, looking at the test workflow first.

### CODE REVIEW

**Review by caugner — COMMENTED** [review]
Triggered a [dev build](https://github.com/mdn/yari/actions/runs/3488015309) to test the changes.

**Comment by caugner** [comment]
> Dev build for [037fa35](https://github.com/mdn/yari/commit/037fa35045efc9f1f9c832aa9b2bd484b98f2f71) was deployed to: https://pr7612.content.dev.mdn.mozit.cloud/

LGTM.

**Comment by caugner** [comment]
> Dev build for [aafc160](https://github.com/mdn/yari/commit/aafc1608c4c99a6c791c820091363f1210dcb3eb) was deployed to: https://pr7612.content.dev.mdn.mozit.cloud/

LGTM:

- Specifications and BCD sections [work](https://pr7612.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/dialog#specifications)
- Sections (obviously) and Summary [work as well](https://pr7612.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/dialog/index.json)

**Review by queengooborg — APPROVED** [review]
LGTM!

**Pull request merged**
