### PR TITLE
fix: ESLint no-lonely-if

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by peterbe** [comment]
Did you make this one with the `--fix` thing?

**Comment by nschonni** [comment]
Partially, it couldn't fix the one with a comment between the `else` and `if`. Manually combined the 2 `if`s for the throw that may have been unrelated and just adjacent

**Comment by peterbe** [comment]
> Partially, it couldn't fix the one with a comment between the `else` and `if`. Manually combined the 2 `if`s for the throw that may have been unrelated and just adjacent

No offense, but they'll review it a lot more carefully :)
That if-logic in there was already pretty hairy. 

I'll review the code but I'll also take care of a couple of flaws too.

**Review by peterbe — APPROVED** [review]
I was able to fix all of these flaws: https://github.com/mdn/content/pull/2075

**Pull request merged**
