### PR TITLE
fix: 'sans-sans' should be 'sans-serif'

### LINKED ISSUE #6664: CSS: 'sans-sans' instead of 'sans-serif'
### Summary

In https://github.com/mdn/yari/blob/main/client/src/app.scss#L19, one of the `font-family` listed is `sans-sans`. This seems to be a typo, so I'm making a PR to change it to `sans-serif`.

### URL

https://developer.mozilla.org/en-US/docs/Web

### Reproduction steps

1. Go to https://developer.mozilla.org/en-US/docs/Web

### Expected behavior

The last fallback value for 'font-family' should probably be something like `sans-serif` or `serif`

### Actual behavior

The last fallback value for 'font-family' is `sans-sans`

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Screenshot

_No response_

### Anything else?

_No response_

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

### PR DESCRIPTION
**Pull request by dalboris**
## Summary

Fixes #6664

### CODE REVIEW

**Review by fiji-flo — APPROVED** [review]
Thanks!

**Comment by fiji-flo** [comment]
@dalboris sorry I messed up your PR by rebasing the signature got lost. Can you sign the commit again `git commit --amend -S -a` after pulling the changes.

**Review by caugner — CHANGES_REQUESTED** [review]
Unfortunately, your commit signature got lost.

You have two ways to resolve this:
1. Fetch the remote (`git fetch`) and reset your local branch to it (`git reset --hard @{upstream}`), then resign your commit (`git commit --amend -S -a`).
2. Fetch the upstream remote (`git fetch upstream`) and rebase your local branch (`git rebase upstream/main`), which should automatically sign your commit again (if you have enabled it: `git config commit.gpgsign true`).

**Comment by dalboris** [comment]
@fiji-flo @caugner Looks like the commit was never signed to start with: I'm on Linux and didn't have gpgsign enabled. It should now be fixed: let me know if the signature is as expected.

**Review by caugner — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
