### PR TITLE
default branch is 'main' now

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
Perhaps it's worth to fill an issue once this is merged, that shows the error message for people using `master` previously, so that the remediation (as laid out in your discussion thread) can be found easier?

**Comment by peterbe** [comment]
> Perhaps it's worth to fill an issue once this is merged, that shows the error message for people using `master` previously, so that the remediation (as laid out in your discussion thread) can be found easier?

The `yari` repo is a bit of a different monster compared to `mdn/content`. In general, we expect a handful of coders that might work on `mdn/yari` but hopefully tens or hundreds who contribute to `mdn/content`. 
In this repo we can be a little bit more "brutal" and expect more (e.g. git signage).

**Comment by peterbe** [comment]
@schalkneethling @fiji-flo @escattone r?

**Review by escattone — APPROVED** [review]
Thanks @peterbe! If we missed any others, we can open another PR.

**Pull request merged**
