### PR TITLE
fix: change jump to section to table of contents

### LINKED ISSUE #2874: Change "Jump to section" to "Table of contents"
Originally discussed here https://github.com/mdn/content/issues/1371#issuecomment-762091835 and then discussed further here https://github.com/mdn/yari/pull/2839/files#r572166625. A decision was made to headline the table of contents with a "Table of contents" heading.

### PR DESCRIPTION
**Pull request by schalkneethling**
Reword the heading from "Jump to section" to "Table of contents"

fix #2874

### CODE REVIEW

**Review by peterbe — APPROVED** [review]
I prefer this way. It's a bit weird that a ToC is in the sidebar but the expression is so familiar and affording. Whereas "Jump to section" requires me to think and wonder what it might mean.

**Comment by chrisdavidmills** [comment]
This change has been formally approved by the MDN content team.

**Comment by mattiapontonio** [comment]
> a ToC is in the sidebar

Nice point. 💭

**Comment by mattiapontonio** [comment]
Consider opening an issue to refactor this component by removing react features in favor of a more vanilla and accessible solution in line with MDN itself ...

**Pull request merged**
