### PR TITLE
missing translations

### PR DESCRIPTION
**Pull request by peterbe**
@SphinxKnight @hochan222 @mfuji09 This is an experiment I've been working on. It's hard to find the time to really perfect this but I just didn't want to lose the work. If it works, I think it's a lot better than nothing which is what you have now. 

This PR basically makes it so you have 2 dashboards under <http://localhost:3000/:locale/_translations>:

- Translation differences
- Missing translations

Hopefully, if these dashboards work, you'd be able to better get a feeling for which popular English documents your locale is missing. 

I suspect there's a bug related to the progress bar but I guess that can be fixed at some point if we can prove that core functionality actually works.

### CODE REVIEW

**Comment by hochan222** [comment]
- Error Report
  - Error when clicking Differences
  - In case of ja everything works fine
  - In the case of ko, after clicking Differences, the same phenomenon occurs at http://localhost:3000/ko/_translations (sometimes it happens and sometimes it doesn't)
  - In the case of fr,  Error when clicking Differences. http://localhost:3000/ko/_translations OK.

**Comment by peterbe** [comment]
@hochan222 That first screenshot seems to show you're using the wrong branch or something. The new URLs are:

- http://localhost:3000/ko/_translations/differences 
- http://localhost:3000/ko/_translations/missing

And if you go to http://localhost:3000/ko/_translations it should look like this:
Screen Shot 2021-07-30 at 12 59 28 PM

**Comment by hochan222** [comment]
@peterbe  Oh! I'm sorry. It was my branch mistake. However, the same error occurred.

https://user-images.githubusercontent.com/22424891/127688480-3aa871db-eb91-4b53-a437-dd773046e5a4.mov

**Comment by peterbe** [comment]
@hochan222 I still can't reproduce that. My mdn/translated-content and mdn/content are fully up-to-date with upstream `main`. Could it be related to your efforts of trying to convert some `ko` documents to Markdown? Can you try to debug the error to find out what's going on?

You can also go to http://localhost:3000/_translations/differences/?locale=ko directly and inspect the JSON (big!) to try to see why some rows have a `edit` field that is not a valid date.

**Comment by SphinxKnight** [comment]
I concur I've got errors where clicking twice on the Differences header. Basically, http://localhost:3000/fr/_translations/differences?sort=differences&sortReverse=true was failing locally (fresh yari / content / translated-content)
image

**Comment by hochan222** [comment]
> I concur I've got errors where clicking twice on the Differences header. Basically, http://localhost:3000/fr/_translations/differences?sort=differences&sortReverse=true was failing locally (fresh yari / content / translated-content)

Could you please check my PR above? I thought that the cause was that the date did not have a null guard, so I gave the following PR.

**Comment by peterbe** [comment]
> I concur I've got errors where clicking twice on the Differences header.

@SphinxKnight I can't reproduce this. And I wonder if it's because both you and @hochan222 perhaps have your OS set to some locale that isn't English US. So perhaps I'm just lucky. The way we treat dates in the Node code should be as strings in ISO format. E.g. `'2021-04-02T11:50:14.000Z'`.

Another explanation is that it could be that your git history is different from mine. Myterious. Can you try this little Python script to find out what's in your JSON from the server:

```python
import json
from urllib.request import urlopen

r = urlopen("http://localhost:3000/_translations/differences/?locale=fr")
for doc in json.load(r)["documents"]:
    if not doc["edits"]["modified"] or not doc["edits"]["parentModified"]:
        print(doc)
```

On my (lucky) laptop, I get nothing. 

Another thing you can perhaps do is to open `client/src/translations/differences/index.tsx` around line 684 and put:
```js
  console.log({
    modified: edits.modified,
    parentModified: edits.parentModified,
  });
```
and see what happens in your Web console.

**Comment by hochan222** [comment]
@peterbe I have summarized the cause in the following PR, could it be of any help?

https://github.com/peterbe/yari/pull/14

**Comment by mfuji09** [comment]
@peterbe
Sorry, how can I start a server listening localhost:3000?

**Comment by SphinxKnight** [comment]
@peterbe sorry for my mistake, I didn't run `yarn dev` but the ""usual"" `yarn install`, `yarn start` like I do over mdn/content.
When using `yarn dev` I don't have the issue described earlier.

I get nothing from the test python script.

@mfuji09 in order to get a local server listening on 3000, you need to clone this repository, configure an `.env` file like with `mdn/content`, run `yarn install` then `yarn dev`

**Comment by peterbe** [comment]
@hochan222 See @SphinxKnight 's comment just above. He realized that running `yarn install && yarn dev` when checking out this branch made the problem go away. Perhaps that can resolve yours too.
And would you mind trying that above-mentioned little Python script to try to figure out why some docs don't have a `.modified`.

**Comment by hochan222** [comment]
> @peterbe sorry for my mistake, I didn't run `yarn dev` but the ""usual"" `yarn install`, `yarn start` like I do over `mdn/content`.
> When using yarn dev I don't have the issue described earlier.
> I get nothing from the test python script and console log.

Sorry for my mistake. I had the same problem as @SphinxKnight. After running `yarn dev`, no issues occurred. Everything works fine with no problems. Thank you!

**Comment by SphinxKnight** [comment]
For the record, since @peterbe left I'm interested in taking this topic (though I'm not sure I've all the abilities to implement that swiftly)

**Comment by hochan222** [comment]
It seems that the current branch has a structural difference from the yari main branch. Right now, I don't have much time because I just got a job, but I will help if I have time later.

**Comment by peterbe** [comment]
@hochan222 @SphinxKnight I have to announce that I no longer work for Mozilla so I've left the MDN project. If you thin this tool is handy, please redirect your feedback to @escattone @fiji-flo or @schalkneethling

**Comment by SphinxKnight** [comment]
Thanks a lot for starting this @peterbe, I hope I'll be able to continue this kind of dashboard for l10n (though the plate is quite full of markdown-ish things right now :)) 
All the best for what's next :)

**Comment by SphinxKnight** [comment]
It might be useful to continue the work on this on #4741 in order not to flood Peter's mention/lock feedback loop.

**Comment by caugner** [comment]
Closing in favor of #4741 (already merged).

**Pull request closed without merging**
