### PR TITLE
fix(release-please): fix config structure

### PR DESCRIPTION
**Pull request by caugner**
### Problem

The [previous config fix](https://github.com/mdn/yari/pull/10411) accidentally added all config options under the `packages` key.

### Solution

Fix the config structure.

---

## How did you test this change?

We'll see once this is merged.

### CODE REVIEW

**Comment by caugner** [comment]
@OnkarRuikar Can you take a look? 🙏

**Comment by caugner** [comment]
@OnkarRuikar Can you approve the PR? Then I can merge. 😉

**Review by OnkarRuikar — APPROVED** [review]

**Comment by OnkarRuikar** [comment]
:crossed_fingers: You need to close and retrigger the release PR. How did you recreate the last release pr?

**Comment by caugner** [comment]
> 🤞 You need to close and retrigger the release PR. How did you recreate the last release pr?

release-please automatically runs on pushes to `main` and it should create or update the release PR.

**Comment by OnkarRuikar** [comment]
> > 🤞 You need to close and retrigger the release PR. How did you recreate the last release pr?
> 
> release-please automatically runs on pushes to `main` and it should create or update the release PR: https://github.com/mdn/yari/actions/runs/7710098741/job/21012724255

Looks like it worked! ;) 
https://github.com/mdn/yari/pull/10407/files

**Pull request merged**
