### PR TITLE
chore(macros/LearnSidebar): add "HTML forms in legacy browsers"

### PR DESCRIPTION
**Pull request by kashyapkaki**
## Summary

Fixes https://github.com/mdn/yari/issues/9349

### Problem

Learn/Forms/HTML_forms_in_legacy_browsers page is missing from the MDN Web Forms sidebar.

### Solution

Added "HTML form in legacy browsers" under the "Advanced forms articles" sidebar subsection.

## Screenshot

image

---

## How did you test this change?

Verified by running the code locally.

### CODE REVIEW

**Review by caugner — APPROVED** [review]
LGTM, but I defer to @wbamberg about whether this is the right position in the sidebar.

**Comment by kashyapkaki** [comment]
> @kashyapkaki Oh, it looks like some of your commits aren't signed. Can you please have a look [at this failing check](https://github.com/mdn/yari/actions/runs/5414546772/jobs/9957464856?pr=9202) and follow the instructions? 🙏

Thanks for tagging. Yes, I've signed and pushed the commit again. Thank you.

**Comment by kashyapkaki** [comment]
> > @kashyapkaki Oh, it looks like some of your commits aren't signed. Can you please have a look [at this failing check](https://github.com/mdn/yari/actions/runs/5414546772/jobs/9957464856?pr=9202) and follow the instructions? 🙏
> 
> Thanks for tagging. Yes, I've signed and pushed the commit again. Thank you.

@caugner Is that still showing I haven't signed the commits?

**Comment by caugner** [comment]
> Is that still showing I haven't signed the commits?

Unfortunately, yes. 🤔 Could you please try to follow these steps:

1. Make sure you don't have any uncommitted changes.
2. Run `git stash` just to be safe.
3. Run `git checkout main` and then `git reset --hard 135c236` and finally `git push --force`

This should put the branch in a state where it has a single verified commit.

**Pull request merged**
