### PR TITLE
start pruning again

### PR DESCRIPTION
**Pull request by peterbe**
This is phase 1 (of 2) where we start pruning again. 

Once we land this, we let it build Stage and that should delete a page such as https://developer.allizom.org/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_ISP_hooks (watch out for CloudFront caching!)
But not only will archived content disappear, other pages that should have been pruned weeks ago should also disappear such as https://developer.allizom.org/en-US/docs/Web/HTML/Using_the_Application_cache too (note that this page 200 OKs but fails because it's JS bundle is way too old)

### CODE REVIEW

**Comment by peterbe** [comment]
I'm testing it out [on Dev](https://github.com/mdn/yari/actions/runs/1034354578)  but now I realize it's silly because Dev never built archived content. And Dev's S3 bucket auto-cleans up old files.

**Comment by peterbe** [comment]
@escattone The `--prune` option in the deployer would freak out if not a single line from the `archived.txt` file came out. Removed that check now.

**Review by escattone — APPROVED** [review]
Thanks @peterbe!

**Comment by peterbe** [comment]
[Stage is building](https://github.com/mdn/yari/actions/runs/1034742062)
Note-to-self; run a complete CloudFront purge for stage at about 2:30pm. 
Also, remember to study the stdout logging from deployer now. It should mention how much was pruned.

**Comment by peterbe** [comment]
Stage build finished.

```
Upload files from: ../client/build
Upload redirects from: /home/runner/work/yari/yari/mdn/content/files, /home/runner/work/yari/yari/mdn/translated-content/files
Upload into: main/ of mdn-content-stage
Total pending redirect uploads: 36,281 (70.6ms)
Total pending file uploads: 168,373 (4.2s)
Total existing S3 objects: 285,232 (1m25s)
Total uploaded files: 76,628 (4962.3MB)
Total uploaded redirects: 36,281 
Total skipped files: 91,745 matched existing S3 objects
Total upload/skip time: 10m50s
Total pending task deletions: 80,568
Total deleted keys: 80,568
Done in 16m2s.
```

This is yesterday's regular daily build (for Stage)
```
Upload files from: ../client/build
Upload redirects from: /home/runner/work/yari/yari/mdn/content/files, /home/runner/work/yari/yari/mdn/translated-content/files
Upload into: main/ of mdn-content-stage
Total pending redirect uploads: 36,367 (49.4ms)
Total pending file uploads: 169,008 (3.2s)
Total existing S3 objects: 285,201 (1m23s)
Total uploaded files: 76,224 (5090.2MB)
Total uploaded redirects: 36,367 
Total skipped files: 92,784 matched existing S3 objects
Total upload/skip time: 8m45s
Done in 10m11s.
```

**Pull request merged**
