### PR TITLE
fix(macros/cssxref): correct URL generation for data types and functions

### LINKED ISSUE #8755: `{{CSSXref}}` handles CSS functions incorrectly
### Summary

Since https://github.com/mdn/content/pull/14006:

  1. using this macro for CSS functions with parentheses in its parameter, e.g. `{{CSSXref("abs()")}}`, results in flaws, as parentheses are still kept in the URLs;
  2. `:host()` and `fit-content()` needs special-casing to append `_function` in the URLs.

Also:

  1. https://github.com/mdn/content/pull/26395 added `<overflow>`, which needs special-casing, too.
  2. The examples in `cssxref.ejs` need correction.

### Proposed solution

On [Line 53](https://github.com/mdn/yari/blob/main/kumascript/macros/cssxref.ejs#L53):

```diff
- // Deal with CSS functions by removing ()
- var slug = $0.replace(/&lt;(.*)&gt;/g, '$1');
+ // Deal with CSS data types and functions by removing <> and ()
+ var slug = $0.replace(/&lt;(.*)&gt;/g, "$1")
+     .replace(/\(\)/g, "");
  
- // Special case <color>, <flex>, and <position>
- switch ($0) {
-     case '&lt;color&gt;':
-         slug = 'color_value';
-         break;
- 
-     case '&lt;flex&gt;':
-         slug = 'flex_value';
-         break;
- 
-     case '&lt;position&gt;':
-         slug = 'position_value';
-         break;
- }
+ // Special case <color>, <flex>, <overflow>, and <position>
+ if (/^&lt;(color|flex|overflow|position)&gt;$/.test($0)) {
+     slug += "_value";
+ }
+ 
+ // Special case :host() and fit-content()
+ if (/^(:host|fit-content)\(\)$/.test($0)) {
+     slug += "_function";
+ }
```

### URL

https://github.com/mdn/content/pull/26575

### Reproduction steps

1.

### Expected behavior

No flaw for {{CSSXref("url()")}}.

### Actual behavior

A redirection flaw.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

_No response_

### Anything else?

Relates to #8578.
Related discussion: https://github.com/orgs/mdn/discussions/369

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

### PR DESCRIPTION
**Pull request by yarusome**
## Summary

Fixes #8755.

### Problem

  1. `{{CSSXref}}` Generated URLs for CSS functions contain extra parentheses.
  2. `:host()` and `fit-content()` are not handled correctly.
  3. `<overflow>` is not handled correctly.
  4. The examples in `cssxref.ejs` are outdated.

### Solution

  1. Remove parentheses in `slug`.
  2. Append `_funtion` to `slug`.
  3. Add the data type into the special-case block.
  4. Update examples according to current results.

---

## How did you test this change?

Run the following code in the console:

```js
// Only return the URL
function CSSXref(arg0, arg1 = "", arg2 = "") {
  const lang = "en-US"; // for convenience
  let url = "";
  let urlWithoutAnchor = "";
  let displayName = (arg1 || arg0);
  
  // Deal with CSS data types and functions by removing <> and ()
  let slug = arg0.replace(/&lt;(.*)&gt;/g, "$1")
      .replace(/\(\)/g, "");
  
  // Special case <color>, <flex>, <overflow>, and <position>
  if (/^&lt;(color|flex|overflow|position)&gt;$/.test(arg0)) {
      slug += "_value";
  }
  
  // Special case :host() and fit-content()
  if (/^(:host|fit-content)\(\)$/.test(arg0)) {
      slug += "_function";
  }
  
  const basePath = `/${lang}/docs/Web/CSS/`;
  urlWithoutAnchor = basePath + slug;
  url = urlWithoutAnchor + arg2;
  
  return url;
}

// Test cases adpated from 'cssxref.test.ts'
const TEST_CASE = [
  "display",
  "attr()",
  ":host()",
  "length",
  "&lt;length&gt;",
  "&lt;color&gt;",
  "&lt;overflow&gt;"
];

for(const caseInput of TEST_CASE) {
  console.log(CSSXref(caseInput));
}

/* Expected output:
   /en-US/docs/Web/CSS/display
   /en-US/docs/Web/CSS/attr
   /en-US/docs/Web/CSS/:host_function
   /en-US/docs/Web/CSS/length
   /en-US/docs/Web/CSS/length
   /en-US/docs/Web/CSS/color_value
   /en-US/docs/Web/CSS/overflow_value
*/
```

### CODE REVIEW

**Comment by yarusome** [comment]
The unit test is complaining about `pageType` (?)

**Comment by caugner** [comment]
@yarusome The unit test does not access mdn/content, but instead uses some mock pages, and the mocked `attr` page still uses parentheses:

https://github.com/mdn/yari/blob/f6e5179dfa8574bb30ed29b1b4c6a1a47a6e70d7/kumascript/tests/macros/cssxref.test.ts#L37-L45

Updating those urls should fix the failing test.

**Comment by yarusome** [comment]
@caugner Thanks for the hint. All unit tests pass now.

**Review by caugner — APPROVED** [review]
LGTU (@argl @fiji-flo @caugner)

**Pull request merged**
