### PR TITLE
back button and document state working

### LINKED ISSUE #927: Back button broken due to storing of doc in state
Here's how to reproduce:

1. `yarn clean && yarn start`
2. In another termainal: `node content build -l en-us -f web/html/element`
3. Go to http://localhost:5000/en-US/docs/Web/HTML/Element/aside/
4. Click "HTML elements reference" in the breadcrumb (second to last, but last blue link in the breadcrumb)
5. Now hit the back button. It doesn't revert back to the `<aside>: The Aside element` page

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #927

Pretty sure this is solving all our worldly problems, but it's late and perhaps my brain is a bit fried.

### CODE REVIEW

**Comment by peterbe** [comment]
I'm closing this on behalf of @Gregoor 's nudge that this is the kind of thing an automated headless test should keep an eye on.

**Comment by peterbe** [comment]
@Gregoor Now with 101% more tests. 
I'm quite pleased with this. 
Because I wrote the fix before I wrote a breaking test, I instead started a new branch off `master` that did the test (see the new addition to `headless.test.js`) and unsurprisingly it failed. 
Then I went back to *this* branch and merged that branch into here and now the tests pass. Yay!

r?

By the way, here's how I tested it manually. 
1. `yarn clean && yarn start:functional`
2. Visit http://localhost:3000/en-US/docs/Web/Foo and http://localhost:3000/en-US/docs/Web 
3. Change the port to http://localhost:5000/en-US/docs/Web/Foo 
4. Click "Web technology for developers" in the breadcrumb. 
5. Click browser back button. 
6. End up back on the Foo page?

**Comment by Gregoor** [comment]
This is great! Thank you for adding a test for it, I love it. On reductio I happened to have replaced document fetching with useSWR which also stealthily seemes to have fixed the same issue. Looking forward to running the new test on the branch and see whether it breaks.

**Comment by peterbe** [comment]
> useSWR which also stealthily seemes to have fixed the same issue

That's always scary. I had that same problem on songsearch where I used a custom wrapper on `fetch` that basically memoized the fetches. That's why it took a long time to notice that it re-mounted the whole thing because the memoization fetch was so fast my eyes didn't notice and I didn't see the traffic in the web console.

**Pull request merged**
