### PR TITLE
git move instead of unlink

### PR DESCRIPTION
**Pull request by fiji-flo**

### CODE REVIEW

**Review by peterbe — CHANGES_REQUESTED** [review]
Won't this cause 2 commits? I.e. two distinct git SHAs. 

Look at this example:

```
▶ git init --initial-branch=main

▶ echo '<html>' > index.html

▶ git add index.html && git commit -m initial

▶ echo '# Markdown' > index.md

▶ cat index.md > index.html

▶ git mv index.html index.md

▶ git commit -a -m conversion

▶ git log
commit c5b5ecdf3203e17248d286b73fb1b35efed28aed (HEAD -> main)
Author: Peter Bengtsson <mail@peterbe.com>
Date:   Wed Jul 14 10:57:54 2021 -0400

    conversion

commit ba0b9eaefc0f6c62387618d8d88008cffdddb330
Author: Peter Bengtsson <mail@peterbe.com>
Date:   Wed Jul 14 10:56:09 2021 -0400

    initial commit
```

Am I missing something? That'll create 1 commit for the conversion. 

In my scenario here above, I first wrote `index.md` to disk and then put its content into the `index.html`, right before the `mv`.

**Comment by fiji-flo** [comment]
**squash**

https://github.com/fiji-flo/content/blob/test-squash/files/en-us/web/javascript/index.md

was merged via squash (with two commits originally)

**no-squash**

https://github.com/fiji-flo/content/blob/test-no-squash/files/en-us/web/javascript/index.md

was merged via merge commit (with two commits)

---

Both don't have the proper history on GitHub (maybe there's a setting or their magic doesn't work).

However if you check these branches out locally and run:

```sh
git log --follow --oneline files/en-us/web/javascript/index.md

# squash:
51fb09aaf (HEAD -> test-squash, origin/test-squash) Convert js to markdown (#1)

# no-squash:
8f5603b50 (origin/convert-js-to-markdown, main, convert-js-to-markdown) web/javascript to markdown - part 2
6ea4717f3 web/javascript to markdown - part 1
1da407d86 Fix: Moving some http links to https (#4633)
8b757de7a Update outdated info on ECMAScript specs (#4196)
2c6f017de Remove button class (#4088)
4281baca8 Remove summary and seoSummary classes, where they have an effect (#4085)
ae6bd6510 Fix broken fragment link in “JavaScript” doc (#4047)
e4a9ff137 Drop link to outdated “New in JavaScript” doc (#2481)
7b5fe6bf7 remove class=external from web/javascript (#2491)
390fd8a7d expand helpful tools section (#2463)
f99dbe913 fixing some sectioning flaws (#2035)
0d8c3f1ce fix: learn to become a webdev callout (#1295)
e82763bf0 fix: Empty dt and missing dd (#593)
dad0283e6 fix: Closed and re-opened em and strong tags (#508)
c617e2e9d dump 2020-12-07 (#158)
cbe151a06 initial en-us content checkin
```

**Comment by peterbe** [comment]
Are you saying it's impossible to edit and rename a file, whilst using the "Squash and merge" policy, and keeping the GitHub history? If so, don't let me stand in your way.

**Comment by fiji-flo** [comment]
@peterbe yes. That's the best way forward. Can you take another look?

**Review by peterbe — APPROVED** [review]

**Comment by peterbe** [comment]
So, if you need to retain the file history, I guess you might need to temporarily disable that all PRs should "Squash and merge". Up to you guys.

**Pull request merged**
