### PR TITLE
fix: active state of breadcrumb items to remove background color from >

### LINKED ISSUE #1865: breadcrumb's > should be out of the :active state of the breadcrumb
The Arrow should be out of the Blue rectangle.

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/pull/1864#issuecomment-734832487_

### PR DESCRIPTION
**Pull request by akhil-gautam**
image

Fixes #1865

### CODE REVIEW

**Comment by schalkneethling** [comment]
Hey @akhil-gautam, thank you for the pull request. Could you please have a look at the link below and ensure that your commits are signed? Thank you

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/about-commit-signature-verification

**Review by schalkneethling — APPROVED** [review]
Other than https://github.com/mdn/yari/pull/1909#issuecomment-737353045, this is all good. Thanks again.

**Comment by mattiapontonio** [comment]
Also in another PR but a 1em padding would be fine in my opinion. Or change the color on active anchors and not the background since it is an element that must be in line and therefore problems of alignment with the other words in the sentence.

**Comment by akhil-gautam** [comment]
> Hey @akhil-gautam, thank you for the pull request. Could you please have a look at the link below and ensure that your commits are signed? Thank you
> 
> https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/about-commit-signature-verification

@schalkneethling  I have tried signing-off again. I do have the gpg's in place. Please let me know if it works.

**Pull request merged**
