### PR TITLE
h2m: Add l10n-pt-br support for cards

### LINKED ISSUE #6803: [h2m] Add support to notes, callouts, and warnings on pt-br
This issue was discussed over [issue #7291 at mdn/translated content](https://github.com/mdn/translated-content/issues/7291).

It was pointed out by @cw118 the need for creating a file named `pt-BR.json` in the folder `markdown/localizations` to allow notes, callouts, and warnings to use translated keywords in Brazilian Portuguese.

### PR DESCRIPTION
**Pull request by bpires**
## Summary

  Fixes #6803.

### Problem

  Lack of support to notes, callouts, and warnings on pt-br

### Solution

1. Create `yari\markdown\localizationspt-BR.json`
2. Add Markdown localization spec for rendering translated cards properly on Brazilian Portuguese

### CODE REVIEW

**Comment by fiji-flo** [comment]
@mdn/yari-content-pt-br could you confirm this?

**Review by caugner — APPROVED** [review]
I verified that these are the Portuguese terms already used in translated-content.

**Comment by caugner** [comment]
Thank you for your PR. 🙏 

We require that all commits are signed.
Please see the documentation [about signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) and [how to sign yours](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) on GitHub.

**Comment by bpires** [comment]
Thank you @caugner for your review! 

Sorry for the verification issue and I appreciate the guidance. I'll look into it ASAP and make sure all my commits are verified from now on.

**Comment by caugner** [comment]
@bpires The easiest way to add the commit signature here is to run `git reset 4ebeede6e4e65798b315650bb97a05aac0471308` in this branch, followed by `git commit --amend -S` and `git push -f`.

**Comment by bpires** [comment]
Can you check if everything is ok now @caugner? Thank you for your assistance and pardon my lack of experience.

**Comment by caugner** [comment]
Thank you @bpires for your contribution, and no need to apologize. You're doing awesome! 🎉

**Pull request merged**
