### PR TITLE
hide toolbar for frozen locales

### PR DESCRIPTION
**Pull request by fiji-flo**

### CODE REVIEW

**Review by peterbe — APPROVED** [review]
I didn't even test this one. It looks safe and sane.

**Comment by Elchi3** [comment]
Well, I have no toolbar anymore locally. What do I need to set to get it back?

**Comment by fiji-flo** [comment]
For `en-US` content? Can you share the local url?

**Comment by Elchi3** [comment]
Yes e`n-US` but nevermind, I guess I was hitting some cache.

**Pull request merged**
