### PR TITLE
fake whoami in dev deployments

### LINKED ISSUE #1504: Fake whoami in dev deployments
When testing a branch on `*.content.dev.mdn.mozit.cloud` it will not redirect request to `/api/v1/whoami` to Django. For good reasons too because there's never a cookie you can have that will ever return anything useful since you won't be able to sign into Kuma on one of those domains anyway. 

https://main.content.dev.mdn.mozit.cloud/api/v1/whoami needs to 200 OK.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #1504

### CODE REVIEW

**Comment by peterbe** [comment]
@escattone r? ping

**Comment by escattone** [comment]
@peterbe Sorry for the delay. I started reviewing this, hit some problems, and then was overwhelmed with other tasks. I might not get to this until next week.

**Comment by peterbe** [comment]
ping
I'm not desperate for this but it would be nice to have.

**Comment by escattone** [comment]
@peterbe Should we close this? I don't think we need it.

**Pull request closed without merging**
