### PR TITLE
Mark beta/nightly/planned browsers releases as preview

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates our compatibility table rendering to check if a specified release has been marked as "beta", "nightly", or "planned" in BCD's data, and if so, marks it as a preview release.  This was opened in response to https://github.com/mdn/browser-compat-data/issues/15073, where the user was confused because the table marked "full support" for Safari 15.4, which is currently unreleased as of the time of writing.

To check the functionality of this PR, visit the following three pages:
- No Preview Browsers: http://localhost:3000/en-US/docs/Web/API/Document/createElement
- Normal "preview" Marking: http://localhost:3000/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription
- Safari 15.4 Marked Preview:﻿http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

### CODE REVIEW

**Review by schalkneethling — APPROVED** [review]
From a functional perspective, this works great! Thanks, @queengooborg

**Comment by ddbeck** [comment]
Thanks for this PR, Vinyl. However, some redesign changes coming have me uncertain about whether this would regress immediately. If you don't mind, I'd like to hold onto this until next week or so and then figure out next steps.

**Comment by queengooborg** [comment]
I have just merged the latest `main` with the redesign changes, so this is now ready for review once again!

**Comment by fiji-flo** [comment]
Thanks you so much.

**Pull request merged**
