### PR TITLE
chore: master -> main branch

### PR DESCRIPTION
**Pull request by nschonni**
https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-

### CODE REVIEW

**Comment by nschonni** [comment]
@chrisdavidmills @peterbe this probably should come from your side, I just did quick find when I saw they'd rolled out the proper rename support

**Comment by peterbe** [comment]
I think we should do it. Let's merge as many open PRs as possible to make it easier for people. 
The question is, when do we do this. 

Also, making sure @escattone and @fiji-flo and @schalkneethling are included in this conversion.

**Comment by Elchi3** [comment]
> Let's merge as many open PRs as possible to make it easier for people.

If I understand it correctly, GitHub will take care of open PRs and retarget them. I saw this in other projects' open PRs:

> Base automatically changed from master  to main  13 hours ago

**Comment by escattone** [comment]
👍 I'm all for this. I guess there's never a perfect time, but if @fiji-flo and @schalkneethling agree, we could pick any time once we understand all of the consequences. Are there any consequences for the content and/or translated content repos? Do we display any URL's to Yari on MDN that include the `master` branch?

**Comment by nschonni** [comment]
Just tested this out on another repo with some open PRs
image

**Comment by nschonni** [comment]
Looks like it does redirects as well. EX: https://github.com/canada-ca/template-gabarit/blob/master/README.md
I'm guessing they'll add a block post "soon" to better describe it

**Comment by schalkneethling** [comment]
Go for it!

**Comment by nschonni** [comment]
@peterbe looks like most already got fixed, but found one leftover one after the rebase

**Review by peterbe — APPROVED** [review]

**Comment by escattone** [comment]
Thanks @nschonni

**Pull request merged**
