### PR TITLE
prototype ace

### PR DESCRIPTION
**Pull request by fiji-flo**

### CODE REVIEW

**Comment by peterbe** [comment]
Maybe you should add this to https://github.com/mdn/yari/projects/4 ?

**Comment by peterbe** [comment]
I'm not sure what to do with this. *Choosing* Ace is probably more interesting than how you did it. I'd love to see a justification and research for why it's better than Monaco (e.g. [`react-monacoeditor`](https://wangchujiang.com/react-monacoeditor/) or Codemirror@next or whatever else is an option. 

Perhaps, turn this PR into a draft and retrofit an issue where the discussion can happen, and then we can triage from there?

**Comment by schalkneethling** [comment]
@fiji-flo Is this still something we want to pursue or, can we close the PR? Thanks!

**Comment by fiji-flo** [comment]
Thanks, closing!

**Pull request closed without merging**
