### PR TITLE
Replace Details of the object model with Using classes in JS sidebar

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Summary

In accordance with https://github.com/mdn/content/pull/18542

### Solution

---

### After

---

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
Approving from the content side.

**Review by awxiaoxian2020 — APPROVED** [review]

**Comment by Josh-Cena** [comment]
Wondering who I can poke for this. @mdn/mdn-community-engagement?

**Comment by teoli2003** [comment]
@mdn/core-dev Can anybody review this? Thank you!

**Review by LeoMcA — APPROVED** [review]
lgtm

**Pull request merged**
