### PR TITLE
fix(client/public): avoid global variable

### LINKED ISSUE #9597: Unreasonable global variables
### Summary

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors

For example, I open the developer tools on the page and enter the following command in the console

```
let a = 1
let b = 2
let c = 3
```

I will get the following error

`Uncaught SyntaxError: Identifier 'c' has already been declared`

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors

### Reproduction steps

Open https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors

Open developer tools

Enter the following command in the console

```
let a = 1
let b = 2
let c = 3
```

### Expected behavior

No error reported

### Actual behavior

Error

`Uncaught SyntaxError: Identifier 'c' has already been declared`

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

image

### Anything else?

https://github.com/mdn/yari/blob/231d6aab8f1c8efe159d268c261446c5b7ae12d9/client/public/index.html#L112

The global variable c is defined here

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

### PR DESCRIPTION
**Pull request by mtrucc**
## Summary

Fixes #9597

### Problem

Unreasonable global variables 'c'

### Solution

https://github.com/mdn/yari/blob/231d6aab8f1c8efe159d268c261446c5b7ae12d9/client/public/index.html#L112

Replace the global variable named 'c' to 'themeConfig'

---

### After

---

## How did you test this change?

Open developer tools

Enter the following command in the console

```
let a = 1
let b = 2
let c = 3
```

No error reported

### CODE REVIEW

**Review by LeoMcA — CHANGES_REQUESTED** [review]
I'd leave the variable as-is, but instead wrap the whole contents of the script tag in an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)

You also need to update the CSP hash as explained in the comment at the top of the script

**Comment by mtrucc** [comment]
> I'd leave the variable as-is, but instead wrap the whole contents of the script tag in an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)
> 
> You also need to update the CSP hash as explained in the comment at the top of the script

Thanks for the tip
I modified the following:
1. Restored variable naming
2. Wrap the whole contents of the script tag in an IIFE
3. Update the CSP hash

**Review by caugner — APPROVED** [review]
Thank you, LGTM! 🙌

**Comment by caugner** [comment]
@mtrucc It looks like you just ran `git merge main` or similar after enabling `commit.gpgsign`.

Can you please run `git rebase main --exec "git commit --amend --gpg-sign --no-edit"` once, which should re-sign your first two commits, and then `git push --force`? 🙏

**Comment by mtrucc** [comment]
> @mtrucc It looks like you just ran `git merge main` or similar after enabling `commit.gpgsign`.
> 
> Can you please run `git rebase main --exec "git commit --amend --gpg-sign --no-edit"` once, which should re-sign your first two commits, and then `git push --force`? 🙏

The command has been executed. Please try it again. Thanks.

**Comment by mtrucc** [comment]
The PR contained in contains 2 unverified commits
Do a fork and commit again
https://github.com/mdn/yari/pull/9619

**Pull request closed without merging**
