### PR TITLE
eslint test more

### PR DESCRIPTION
**Pull request by peterbe**
Testing a few more `.js` files and picking up some good ideas from https://github.com/mdn/yari/pull/2157/files

### CODE REVIEW

**Comment by peterbe** [comment]
@nschonni I carefully picked out a very limited set of ideas from your PR. I prefer this way of making smaller changes. 
The list of "includes" is getting a bit silly. Perhaps doing an exclusion (`.eslintignore`) file is better. But one thing I found is that if you use a `.eslintignore` and `eslint .` it will run through all the `.js` files I have here in my repo that are git ignored. For example, `peterbe__find_redirect_chains.js` is a little hack (one of many many) that I've added to `.git/info/exlude`. 
I don't want to have to pepper the `.eslintignore` with all my personal git ignores.

**Comment by fiji-flo** [comment]
@peterbe shall we do this (probably rebase/merge before doing so)

**Comment by peterbe** [comment]
> @peterbe shall we do this (probably rebase/merge before doing so)

I don't understand the question.

**Comment by peterbe** [comment]
Ok. Simplified, so it now only checks all `kumascript` and the `testing`.

**Comment by peterbe** [comment]
@fiji-flo ping r?

**Review by fiji-flo — APPROVED** [review]

**Pull request merged**
