### PR TITLE
Remove HTMLVersionInline macro

### PR DESCRIPTION
**Pull request by Elchi3**
I've removed all calls for this macro in mdn/content and the macro isn't called from another macro. In the old world, I would also check translations and remove calls there, but I'm not sure how to do that now.

So, in theory this would be one macro less to worry about but I marked it as a draft because I'd like to hear about the process for translations first. Thanks! ❤️

### CODE REVIEW

**Comment by mattiapontonio** [comment]
At the moment my ideal translation process is a bot that automatically translates and creates a PR on another repository. This thing happens from every repository on every repository.

**Comment by peterbe** [comment]
@fiji-flo If we merge this, some [200 pages in the translated content](https://github.com/mdn/translated-content/search?q=HTMLVersionInline), when we uplift all, will get KumaScript rendering flaws on all of these.

**Comment by peterbe** [comment]
@Elchi3 For the record...
A) you can set [`BUILD_MACROS_USED_LOGFILE`](https://github.com/mdn/yari/blob/master/docs/envvars.md#build_macros_used_logfile) to get a dump of all macros invoked. If you run `yarn build` (no filtering) you should be able to complement your `grep`'ing too. 
B) I love the idea of deleting one macro at a time. A better approach than attempting to delete them all at the same time. e.g. https://github.com/mdn/yari/issues/1274 and https://github.com/mdn/yari/issues/1727

**Comment by Elchi3** [comment]
> @fiji-flo If we merge this, some [200 pages in the translated content](https://github.com/mdn/translated-content/search?q=HTMLVersionInline), when we uplift all, will get KumaScript rendering flaws on all of these.

Would you accept a PR to https://github.com/mdn/translated-content to fix this and then merge this PR to remove the macro? Or are we fine with having flaws in translations?

**Comment by fiji-flo** [comment]
If it's a simple `sed` command on the translated content we should start writing them down in an issue and we run them before uplifting. I'm right now starting to gather them to, e.g. `IncludeSubnav`.

I just started an [issue](https://github.com/mdn/translated-content/issues/10) to have something for now.

**Comment by peterbe** [comment]
I propose we leave this as a draft until the translated content has all been uplifted.

**Comment by Elchi3** [comment]
I saw other macros got removed, so ready for review/merge now?

**Comment by peterbe** [comment]
Still used in a lot of translated content. ...now that they are all kumascript rendered:
```
MOZILLA/MDN/translated-content  main ✔
▶ rg -i HTMLVersionInline  | wc -l
    1288
```

We do have a plan to write a flaw checker thing, for translated documents only, that highlights what and how out-of-date a translated document is based on analyzing things that are easy to analyze. For example, the presence of certain macros. 
But we don't have that tooling yet. 

The original idea was to pick a couple of KS macros we love and think are important. E.g. `Compat`, `InteractiveExamples`, `LiveSamples` etc. 
But I think we could also consider analyzing all macros. Perhaps, if a translated document uses a macro that the English page does NOT, that's a flaw. I.e. "excess legacy macros" :)

**Comment by Elchi3** [comment]
Okay, closing this until there is something in place to deal with translations.

**Pull request closed without merging**
