### PR TITLE
It's not OK to have diff markers in the content

### LINKED ISSUE #2591: It's not OK to have diff markers in the content
See https://github.com/mdn/content/pull/1313/files#diff-211c5834449afc00013b662e30b57dd49d87b4996b905ad2795481c1eed3df3a

I accidentally messed up the merge conflict resolution in VSCode and accidentally allowed myself to merge it in like that. 
Perhaps in the `mdn/content` repo we should have a husky commit hook that prevents it in the first place, but in Yari, as a last defense, we should NOT allow this to happen at all.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #2591

Screen Shot 2021-01-19 at 10 23 05 AM

### CODE REVIEW

**Comment by peterbe** [comment]
Actually, I change my mind. Instead of (only) doing it in the `yarn build` CLI, let's do it on every actual read. That way you capture it sooner if you, as a writer, try to view it in the previewer too.
Screen Shot 2021-01-19 at 10 25 59 AM

**Comment by peterbe** [comment]
Screen Shot 2021-01-19 at 10 27 43 AM

**Comment by peterbe** [comment]
@escattone perhaps if you have time? r?

**Review by fiji-flo — APPROVED** [review]
Cool

**Pull request merged**
