### PR TITLE
Depreciate htmlattrxref and htmlattrdef

### PR DESCRIPTION
**Pull request by MrBrain295**
## Summary
See mdn/content#25213

### Solution

---

### After

---

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
I confirm that these macros are almost gone from en-US mdn/content.

A small 😢 as I created them a good decade ago. With anchors now generated automatically for definition lists, they became redundant.

**Comment by MrBrain295** [comment]
Now there’s an announcement saying these are deprecated.

**Comment by OnkarRuikar** [comment]
Looks like you also need to update unit tests e.g.
 https://github.com/mdn/yari/blob/697cecb2a9b869503021de175b977bb2cf3470ff/testing/tests/index.test.ts#L453
Change the number to 15.

**Comment by MrBrain295** [comment]
#8551

**Pull request closed without merging**
