### PR TITLE
Depreciate the link macro

### PR DESCRIPTION
**Pull request by MrBrain295**
## Summary
Depreciate the link macro.

### Solution

---

### After

---

### CODE REVIEW

**Comment by yin1999** [comment]
all `{{Link}} macros are removed from mdn/content (mdn/content#19447), ready to depreciate

**Comment by fiji-flo** [comment]
That macro is still used in en-US:
```
$ rg "\{\{\s*link" -i 
files/en-us/glossary/javascript/index.html
21:  <li>The {{Link("/en-US/docs/Web/JavaScript/Guide")}} on MDN</li>
25:  <li>The {{Link("/en-US/docs/Web/JavaScript/reference")}} on MDN</li>

files/en-us/glossary/json/index.html
16:  <li>{{Link("/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON")}} on MDN</li>
```

**Comment by yin1999** [comment]
> That macro is still used in en-US:
> 
> ```
> $ rg "\{\{\s*link" -i 
> files/en-us/glossary/javascript/index.html
> 21:  <li>The {{Link("/en-US/docs/Web/JavaScript/Guide")}} on MDN</li>
> 25:  <li>The {{Link("/en-US/docs/Web/JavaScript/reference")}} on MDN</li>
> 
> files/en-us/glossary/json/index.html
> 16:  <li>{{Link("/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON")}} on MDN</li>
> ```

removed by mdn/content#19447. may need to sync upstream?

**Review by fiji-flo — APPROVED** [review]
my bad `files/en-us/glossary/javascript/index.html` I had some dangling `.html` files in my working directory.

**Pull request merged**
