### PR TITLE
chore(survey): august 2024 web app survey

### PR DESCRIPTION
**Pull request by LeoMcA**
## Summary

https://mozilla-hub.atlassian.net/browse/MP-1405

---

## Screenshots

image

image

---

## How did you test this change?

- `yarn && yarn dev`
- visited http://localhost:3000/en-US/docs/Web/HTML to see banner
- visited http://localhost:3000/en-US/docs/Learn to not see banner

### CODE REVIEW

**Comment by caugner** [comment]
@LeoMcA Can you confirm that the survey has a JavaScript snippet to inform yari about the survey being filled out, to avoid it from being shown up?

**Review by caugner — APPROVED** [review]
Code LGTM.

**Comment by LeoMcA** [comment]
> @LeoMcA Can you confirm that the survey has a JavaScript snippet to inform yari about the survey being filled out, to avoid it from being shown up?

@caugner No, I don't think it does: where do we get that from?

**Comment by caugner** [comment]
> where do we get that from?

https://github.com/mdn/yari/blob/d930863abcb20d52170ab95b670a2676e26f7451/client/src/ui/molecules/document-survey/index.tsx#L124-L125

**Comment by LeoMcA** [comment]
Thanks! I added to the survey, and tested locally.

> PS: We should probably document this also where we define the survey.

Good idea, I've added a similar note

**Pull request merged**
