### PR TITLE
say Auth Disabled on sign in/up too

### PR DESCRIPTION
**Pull request by peterbe**
It doesn't look perfectly the same/sane on all three pages but I don't think it's worth worrying over. The chances of someone ending up on the sign-up page are minuscule. 

Screen Shot 2021-07-21 at 3 49 26 PM

Screen Shot 2021-07-21 at 3 49 37 PM

### CODE REVIEW

**Comment by peterbe** [comment]
To test, you just need to run:

```
export REACT_APP_DISABLE_AUTH=true
yarn dev
```
and then manually type in <http://localhost:3000/en-US/signin>

**Comment by peterbe** [comment]
CC @schalkneethling if you're curious and perhaps you can see that I've committed a crime in terms of how I name and structure the `ui/...` files and folders. :)

**Review by escattone — APPROVED** [review]
Love it, thanks @peterbe!

**Comment by schalkneethling** [comment]
> CC @schalkneethling if you're curious and perhaps you can see that I've committed a crime in terms of how I name and structure the `ui/...` files and folders. :)

Probably more of a molecule, but it is all good 😄  Thank you, Peter.

**Pull request merged**
