### PR TITLE
Use last part of the title page in WebExtAPISidebar

### LINKED ISSUE #2189: WebExtAPISidebar uses part after first dot in title page instead of last part
I started working on mdn/content#336 but I noticed that when tagging properly e.g. [`devtools.panels.create()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/create), the sidebar thinks `panels` is the name to use for the sublist instead of `create()`.

You can reproduce with my PR mdn/content#372 by going to e.g. [`devtools.network` page](http://localhost:5000/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network).

I believe the issue is in this code:

https://github.com/mdn/yari/blob/058ed1836ab5968fb4fb48f3599e52525415b793/kumascript/macros/WebExtAPISidebar.ejs#L44

which should be:

```js
apiComponentName = titlePieces[titlePieces.length - 1];
```

I tried to make a PR but changing the `WebExtAPISidebar.ejs` didn’t seem to affect the rendered page. I noticed that `nodemon` didn’t listen for ejs files but even after relaunching `yarn dev` it still gave me the wrong results.

### PR DESCRIPTION
**Pull request by ariasuni**
E.g. display `create()` for page devtools.panel.create()

Fix #2189

---

Quoting from my first comment on #2189:

> I tried to make a PR but changing the `WebExtAPISidebar.ejs` didn’t seem to affect the rendered page. I noticed that `nodemon` didn’t listen for ejs files but even after relaunching `yarn dev` it still gave me the wrong results.

I tried again and it still doesn’t work. When using `yarn start`, and I try to visit the `devtools.panels` page, I get a “`Error: 404 on /en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/create/index.json: Page not found`”. The only way I get to make yari work is to launch `yarn start` in my local clone of `mdn/content` first, which I believe builds file with its own version of yari. `yarn build` also failed:

<details><summary>output</summary>

```
yarn run v1.22.10
$ cross-env NODE_ENV=production node build/cli.js

Building SPAs...
Wrote /home/ariasuni/projets/divers/yari/client/build/en-us/_spas/404.html

Building Documents...
Building roots: [ '/home/ariasuni/projets/divers/mdn_content/' ]
Error: Unable to figure out locale from files/en-us/developer_guide/editor_configuration with files
    at extractLocale (/home/ariasuni/projets/divers/yari/content/document.js:54:11)
    at /home/ariasuni/projets/divers/yari/content/document.js:200:18
    at /home/ariasuni/projets/divers/yari/content/utils.js:70:19
    at Object.iter (/home/ariasuni/projets/divers/yari/content/document.js:366:15)
    at iter.next (<anonymous>)
    at buildDocuments (/home/ariasuni/projets/divers/yari/build/cli.js:60:14)
    at Se._action (/home/ariasuni/projets/divers/yari/build/cli.js:271:66)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Se.run (/home/ariasuni/projets/divers/yari/node_modules/@caporal/core/dist/index.js:1:27579)
    at async Te._run (/home/ariasuni/projets/divers/yari/node_modules/@caporal/core/dist/index.js:1:32257)

error: Unable to figure out locale from files/en-us/developer_guide/editor_configuration with files
```
</details>

So I couldn’t test the change and hopefully it works.

### CODE REVIEW

**Comment by peterbe** [comment]
Could it be that `/home/ariasuni/projets/divers/mdn_content/` should be `/home/ariasuni/projets/divers/mdn_content/files`?
That was brought up recently as a very confusing thing and I think something was added to the README. But clearly, it's easy to miss things in the README. 

Besides, in your local clone of `yari`, can you use `yarn dev` next time and see if that solves problems?
We still have/had that problem that `nodemon` didn't notice changes to `.ejs` files. But didn't we fix it?

Plus, https://github.com/mdn/yari/issues/2223 might be related to your unfortunate debugging problems. 

We appreciate your patience and contribution!

**Comment by peterbe** [comment]
By the way, if it's true that the system breaks just because you forgot to add the `/files` suffix to the `CONTENT_ROOT` env var, then I think we should write a little code that helps with that. 
E.g.
```javascript
if (path.basename(CONTENT_ROOT) !== 'files' && fs.existsSync(path.join(CONTENT_ROOT, 'files')) {
  console.warn("Hey! Watch out, it appears that your CONTENT_ROOT isn't pointing to the 'files' subfolder. Consider changing it to ...")
}
```

**Comment by ariasuni** [comment]
Ah, yes that was the issue! I tend to unintentionally overlook things like that because I have trouble reading everything and in order. It looked like I should point to the other repository, without noticing the `/files` at the end, expecting an error right away if the directory I pointed to wasn’t correct.

I can confirm the change works, now:

bildo

**Comment by peterbe** [comment]
> because I have trouble reading

Who reads these days? Not me! 
But I script, https://github.com/mdn/yari/issues/2248 :)

**Review by escattone — APPROVED** [review]
@ariasuni Works great, thank you!

**Pull request merged**
