### PR TITLE
build(deps): use caret ranges for all packages except webpack

### PR DESCRIPTION
**Pull request by caugner**
Converts all packages to use caret ranges (`^1.2.3`) instead of a fixed version (`1.2.3`).

### CODE REVIEW

**Comment by schalkneethling** [comment]
@caugner Changes are good but there is now a number of TSErrors which is causing all the things to fail.

**Comment by schalkneethling** [comment]
Still a couple of test failures: https://github.com/mdn/yari/runs/6309112785?check_suite_focus=true

**Comment by caugner** [comment]
@dependabot rebase

**Comment by caugner** [comment]
Converted to draft to wait for #6175 and (subsequently) #6165 to land.

**Comment by caugner** [comment]
@schalkneethling IMO this could be merged, preferably before any other dependency update.

**Review by schalkneethling — APPROVED** [review]

**Pull request merged**
