### PR TITLE
Fix tap size and spacing for tap targets

### PR DESCRIPTION
**Pull request by tannerdolby**
Part of #4060 

Specifically, failed audits in the SEO section: 
- tap targets are overlapping eachother
- tap targets are not appropriately sized (87% of the 48px by 48px requirement)

### CODE REVIEW

**Comment by tannerdolby** [comment]
The majority of failed audits in SEO from Lighthouse was from tap targets overlapping eachother.

Overlapping:
- the `<select>` and `<button>` elements in `<aside class="metadata">` container to change page language
- list items within the `.properties` table
- list items in `<aside class="metadata">` container within `.on-github` div
-  github, twitter, and instagram `::before` icons in footer

> Targets that are smaller than 48 px by 48 px or closer than 8 px apart fail the audit. [tap targets](https://web.dev/tap-targets/?utm_source=lighthouse&utm_medium=devtools)

Since the `.social-icon*` elements in the footer unlike the rest aren't text, but icons. They should have their tap size increased to be closer to the 48px by 48px recommended tap size. This does change their previous "close" together style but I reckon we can mess with styling/spacing on those icons after we ensure their tap size/spacing is passing the SEO audit.

**Comment by tannerdolby** [comment]
I think this might also need to "simmer" until the redesign is concluded as there are some things from `minimalist` that had to be overridden, most of this PR is margin changes, but the `.social-icons` in the bottom footer did receive padding changes as well.

The only advantage of this landing now as opposed to waiting until later (after redesign) to handle would be that the tap targets would be correctly spaced and sized in a Lighthouse audit for SEO. This is part of #4060 and could simmer while the redesign commences, let me know what you think @schalkneethling !

**Comment by schalkneethling** [comment]
@tannerdolby The footer is changed quite a bit as part of the redesign. Could you pick out the pieces that related to the footer and leave the rest? I would be happy to review those. Just ping me for review once you have had a chance to make the change. Thank you.

**Comment by tannerdolby** [comment]
> The footer is changing quite a bit as part of the redesign. Could you pick out the pieces that related to the footer and leave the rest? I would be happy to review those.

Yeah, sure thing @schalkneethling !

**Comment by tannerdolby** [comment]
I removed the changes to footer, ping @schalkneethling

**Review by schalkneethling — APPROVED** [review]

**Pull request merged**
