### PR TITLE
fix: Japanese translation in CompatVersionUnknown.ejs

### PR DESCRIPTION
**Pull request by mfuji09**
fixed incorrect translation.
The old string means:
"Please update to the latest support status."

### CODE REVIEW

**Comment by mattiapontonio** [comment]
@mfuji09 and the new?

**Comment by mfuji09** [comment]
It seems that the test script reports an error whenever I just change the string. The original string is only accepted.
How can I change the translation string?

**Comment by mattiapontonio** [comment]
I'm just saying that those strings should be in the language repository that doesn't currently exist.
Currently I don't know how to fix.

**Comment by chrisdavidmills** [comment]
Can we get some help here @peterbe @escattone ? We are getting a few macro test failures for simple updates, and I am not really sure how to fix them.

**Comment by peterbe** [comment]
@mfuji09 Try merging in the latest `master` into your branch. We upgraded `cheerio` recently and it caused this. 
See [this other fix](https://github.com/mdn/yari/pull/2324/files) that @escattone made yesterday.

**Comment by mfuji09** [comment]
The check has been passed!
Thank you very much, @peterbe and @chrisdavidmills !

**Review by chrisdavidmills — APPROVED** [review]
Excellent, let's get this merged!

**Pull request merged**
