### PR TITLE
chore(macros/HTTPSidebar): improve Spanish locale

### PR DESCRIPTION
**Pull request by edgarrmondragon**
### Problem

Some elements in the spanish version of MDN website's sidebar contain typos, mistranslations or are outright missing a translation.

### Solution

Fixed the typos and corrected some translations.

---

### Before

Screenshot 2024-03-15 at 2 18 52 p m

---

### CODE REVIEW

**Comment by caugner** [comment]
Hi @edgarrmondragon, thank you for opening this PR. 👋 

Please take a moment to fill out the sections in the PR description (you can remove the Screenshots) section. 🙏

**Comment by edgarrmondragon** [comment]
> Hi @edgarrmondragon, thank you for opening this PR. 👋
> 
> Please take a moment to fill out the sections in the PR description (you can remove the Screenshots) section. 🙏

@caugner Done!

**Review by JuanVqz — APPROVED** [review]
@edgarrmondragon thank you for adding these fixes :shipit:

**Comment by JuanVqz** [comment]
@edgarrmondragon thank you for adding these fixes :shipit: 
I don't have enough permissions to approve the remaining workflows, as for Spanish translation, this looks right to be merged!

**Comment by caugner** [comment]
Thanks @edgarrmondragon for the PR and @JuanVqz for the review! 🙌

**Pull request merged**
