### PR TITLE
fix: updates to deep dive article pages

### LINKED ISSUE #4460: UI updates for market research v3
- [x] Reduce survey to a single page
- [x] Add show more link to deep dive article content
- [x] Replace author name with Twitter handle and link
- [x] Replace author title with the date and reading time
- [x] Change copy of CTA to "Take our 1 minute survey"
- [x] Change level 2 heading style as shown in Figma https://www.figma.com/file/y5mZ5Nt7AMSEppuGOfLvnB/MDN-Plus-Experiments?node-id=62%3A672

### PR DESCRIPTION
**Pull request by schalkneethling**
Updates to deep dive article pages for market research v3

fix #4460

### CODE REVIEW

**Review by escattone — CHANGES_REQUESTED** [review]
✅ survey reduced to a single page
✅ `show more` links work 
✅ author name replaced with Twitter link
✅ author title replaced with the date written and reading time
✅ copy of CTA changed to "Take our 1 minute survey"
✅  level 2 heading style changed

There is one issue. Once I click `Submit` for the survey, the experience is strange. The `Submit` button jumps to the left, and the text `Submitting` appears. Here it is at 4G speed:

https://user-images.githubusercontent.com/3743693/129232992-825256d8-0392-47a4-ae3b-a0415dc12ce5.mov

**Comment by schalkneethling** [comment]
> There is one issue. Once I click `Submit` for the survey, the experience is strange. The `Submit` button jumps to the left, and the text `Submitting` appears. Here it is at 4G speed:

Ah yes, that is as before but, we can improve it.

**Review by escattone — APPROVED** [review]
Nice resolution @schalkneethling!

I don't think it's within the scope of this PR, but are the following changes still planned?
- update /en-US/plus/deep-dives page (e.g., removing the third article)
- remove mention of third article on other article pages

**Comment by schalkneethling** [comment]
> update /en-US/plus/deep-dives page (e.g., removing the third article)

Separate PR. We are not removing the third teaser article anymore. Thank you, Ryan!

**Pull request merged**
