### PR TITLE
Add an og:image HTML meta tags

### PR DESCRIPTION
**Pull request by peterbe**
Part of #3693

This definitely seems to work but the URL becomes relative E.g. `<meta property="og:image" content="/mdn-social-share.2f09512a.png"/>`
Let's see if Twitter can cope with it being relative. Otherwise, we might need to hardcode `https://developer.mozilla.org` as a prefix.

### CODE REVIEW

**Comment by peterbe** [comment]
@tannerdolby a review from you here would help @Gregoor a lot :)

**Comment by tannerdolby** [comment]
@peterbe ok I will have a look now :)

**Comment by tannerdolby** [comment]
Looks good to me. I synced with `main` and pulled into this branch and had a look at a few pages. I encountered a loading error on 

- http://localhost:3000/en-US/docs/Web/CSS/:nth-child 
- http://localhost:3000/en-US/docs/Web/CSS/color
- http://localhost:3000/en-US/docs/Web/CSS/font-size

> Error: 500 on /en-US/docs/Web/CSS/:nth-child/index.json: Error: 'ar' not in de,en-US,es,fr,ja,ko,pl,pt-BR,ru,zh-CN,zh-TW

The error didn't happen for http://localhost:3000/en-US/docs/Web/CSS/Attribute_selectors which successfully shows the `og:image` tag on the page. It had a relative path, `<meta name="og:image" content="/mdn-social-share.png">` where I don't see the `%PUBLIC_URL%` but I assume with the addition of `hrefPrefix` that the content will be processed and replaced with cheerio in ssr/render.js to be: 
```
content="%PUBLIC_URL%/mdn-social-share.png --> content="https://developer.mozilla.org/mdn-social-share.png"
```
If I understand the above usage of `PUBLIC_URL`, once those errors I mentioned with /CSS/* pages are remedied I reckon this is ready to merge.

**Comment by peterbe** [comment]
>     * http://localhost:3000/en-US/docs/Web/CSS/:nth-child

Are you sure your stuff is up to date. Do you have `CONTENT_TRANSLATED_ROOT` set? Is that repo up to date?
That URL is working fine for me.

**Comment by peterbe** [comment]
> I didn't see any `og:image` in ssr/render.js where cheerio replaces the content so I assume `%PUBLIC_URL%` is getting the value from `hrefPrefix` elsewhere.

That stuff is happening inside `tool/optimize-client-build.js`. 

What `ssr/render.js` does is that it takes the relevant "state" for a document and combines it with the template `client/build/index.html`. And it does this over and over. So, that that other script does is that post-processes the `client/build/index.html` generates from `yarn build:client`.

**Comment by tannerdolby** [comment]
> Do you have CONTENT_TRANSLATED_ROOT set? Is that repo up to date?

Ah, yes your right. I always remember to use `export CONTENT_ROOT=~/content/files` but didn't include a `CONTENT_TRANSLATED_ROOT` set. After syncing with `mdn/content` and providing `CONTENT_TRANSLATE_ROOT` everything works as expected.

**Review by tannerdolby — APPROVED** [review]

**Comment by peterbe** [comment]
@Gregoor I'm pretty sure that the functionality is good. Much thanks to @tannerdolby 's testing. 
But the `cheerio` code got a bit messy. If you're OK with it, OK. But if you can see an easy refactor that'll make it prettier, I'm all ears.

**Pull request merged**
