### PR TITLE
Use superscript for ≤ in BCT cell text

### LINKED ISSUE #1607: ≤ is ambiguous on MDN
image

https://developer.mozilla.org/en-US/docs/Web/API/MediaSession

It makes me think that Edge supported the feature *until* version 79, not *at-least-since* 79. There is no description about what `≤` actually means. I think this is a problem.

(Transferred from https://github.com/mdn/browser-compat-data/issues/5782)

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #1607

### CODE REVIEW

**Comment by peterbe** [comment]
(@ddbeck || @Elchi3) I'd be happy to review this, more on a "code-level", if you can check if you like the functionality

**Comment by Elchi3** [comment]
Looks good to me. Can we add a title to \<sup>? I think the problem with ≤ is that we don't provide a description what it means.

`<sup title="Supported in version ${version.slice(1)} or earlier.">≤&#xA0;</sup>`

**Comment by mattiapontonio** [comment]
FTR
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup

**Comment by saschanaz** [comment]
>It also doesn't seem like a fair use case of sup.

Hmm, agreed, [the spec says](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-sub-and-sup-elements):

>These elements must be used only to mark up typographical conventions with specific meanings, not for typographical presentation for presentation's sake. For example, it would be inappropriate for the sub and sup elements to be used in the name of the LaTeX document preparation system. In general, authors should use these elements only if the absence of those elements would change the meaning of the content.

`<sup>` here is not supposed to change the meaning so maybe it should instead be just a span with a class. Thoughts?

**Comment by mattiapontonio** [comment]
Let's think in object

```JavaScript
const a = {
 b: "<=",
 version: "1.0.25"
}
```
Change the keys with _known names_.

**Comment by peterbe** [comment]
@mattiapontonio please stop trying to contribute solutions. These guys are experts and they know what `<sup>` is.

**Review by Elchi3 — APPROVED** [review]
Functionality-wise it looks good to me. The `<span>` is probably semantically better and also having it include the number is probably a good thing.

**Comment by Ryuno-Ki** [comment]
> These guys are experts and they know what `<sup>` is.

I'm not sure, whether you intended it, but this sounds a lot like gatekeeping to me.
If they're experts, a polite explanation about why option A is better than B should be possible.

**Comment by peterbe** [comment]
> > These guys are experts and they know what `<sup>` is.
> 
> I'm not sure, whether you intended it, but this sounds a lot like gatekeeping to me.
> If they're experts, a polite explanation about why option A is better than B should be possible.

Fair enough. But the person in mind is/was off topic.

**Comment by mattiapontonio** [comment]
I was not off topic but I was trying to favor the process of eliminating that `<=` which is not a data, it is just a complication that they sent us. When we realize that that string is not a decent object then somehow a solution will be found to get it out of the way.

**Comment by ddbeck** [comment]
@mattiapontonio I want to clear something up: the `≤` comes from the underlying `@mdn/browser-compat-data` package. That package is a separate project, with many dependents other than Yari, and its own list of known issues. Changing that other project is off-topic for the mdn/yari repo. This is not the appropriate venue to discuss changes to the compat data itself.

**Comment by mattiapontonio** [comment]
@ddbeck 
But will there be a change? Because if not in these parts we need to think of a layer that protects us, splits, shapes, etc. If the data arrives like this it is also "good" but where is the final point? does anyone want to shape this table a certain way? does that data only use Yari? Maybe these answers are there but I think of the Front End here which is generating questions and is a simple table. How is it resolved? From what we need to simplify adds complexity, what's the point? Can you give a graphic input on how you imagine the result? I understand the convenience of seeing that those data are updated by hand but some discussion must be done somewhere otherwise this table will never be resolved and is among the top features of MDN.
As far as I am concerned, I also like Can I Use as it does but we must understand that it is not a table, it is an infographic perhaps even pretentious for the information to be communicated. I use the table to know whether or not to use a feature, I don't care about the comparison, it's a habit of the fact that we have tested all browsers. With respect 👍

**Pull request merged**
