### PR TITLE
remove leftover stumptown rendering ingredients

### LINKED ISSUE #1950: Remove leftover code from early stumptown-renderer days
In the early days, when trilobites, roamed the MDN savannah, what is today Yari was once `stumptown-renderer`. A React renderer for the JSON produced by the Markdown inside `stumptown-content`. 
How it worked was quite a bit different. In particular in the `<Document>` component when it loops over the `doc.body` sections. Then Yari was born and adopted a much simpler approach. *Everything* except BCD tables is just HTML prose blobs. No other fancy ingredients. Some day maybe. 
But now we're stuck with "ingredient components" that we never use. We should delete them. 

There might be one exception though! 
Stumptown-content had this great idea around "related links". Instead of the sidebar being a blob of HTML (generated by kumascript) it's instead a simply array of arrays. That is potentially, in my mind, a place I'd love to go with sidebars. So perhaps let's hold to that one a wee bit longer.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #1950
Part of #2877

It's a bit bittersweet but it's the right thing to do. Yari really became something very different from what Stumptown tried to be. 

I think, if we someday decide to revive the idea of structured content with something like "recipes", then that can exist outside of the client code. I.e. still React, but not part of the client. Perhaps some "optional" React code that only happens during the SSR step but when it's done it dumps the rendered HTML in as one big string, and Yari can continue to work as-is and this'll make it agnostic and orthoganol from how legacy content is built.

### CODE REVIEW

**Comment by peterbe** [comment]
The reason this is linked to the https://github.com/mdn/yari/issues/2877 is because deleting these unused ingredients will make the main bundles smaller. In fact, it goes from 67KB to 61KB as you can see here:
Screen Shot 2021-02-10 at 3 35 39 PM

**Comment by mattiapontonio** [comment]
`avatar.png` is **7%**

**Comment by peterbe** [comment]
Note that one of the pieces that only made sense in Stumptown was the idea of the `<SidebarLeaf>` component and rendering a sidebar not based on `doc.sidebarHTML` but on `doc.related_content`. This I still think is a great idea and would "slot in" nicely if we can figure it out. 
To actually figure it out, we need to break down some sidebar macros and figure out a new routine that can produce and array of arrays rather than a big fat blob of HTML produced by some `FooSidebar.ejs`. 
For example, we can write some Node code that traverses the tree and from it produces something like this:

```javascript
[
   {title: "Properties", content: [
    {title: "forEach", uri: "/en-US/docs/JavaScript/Array/forEach"},
    {title: "push", uri: "/en-US/docs/JavaScript/Array/push"},
    ...
  ]},
  {title: "Methods", content: [ ... ]},
  ...
]
```

The Yari builder could get ideas based on the front-matter. E.g. 

```diff
diff --git a/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html b/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html
index 0755aac51..7ff8db372 100644
--- a/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html
+++ b/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html
@@ -8,9 +8,8 @@ tags:
 - Method
 - Prototype
 - Reference
+sidebar: jsref
 ---
-<div>{{JSRef}}</div>
-
 <p>The <code><strong>forEach()</strong></code> method executes a provided function once
   for each array element.</p>
 
```

And what the Yari builder will do is notice the `jsref` identifier in the front-matter and kick of some pure Node JS code (not EJS macros!) that does the figuring out of what the list of lists should be. 

The eventual advantage of all of this is that we can probably make the HTML much slimmer and the sidebar bars will be driven from fresh new pure JS (node) code rather than that cryptic EJS code we have today.

**Comment by peterbe** [comment]
> `avatar.png` is **7%**

One thing at a time. Also, that comment is out of place. You're commenting on a PR, not on the main issue.

**Comment by mattiapontonio** [comment]
> the sidebar bars will be driven from fresh new pure JS (node) code rather than that cryptic EJS code we have today.

This Is good 👍
Hardcoded JSON not programmatic? A porting.

**Comment by peterbe** [comment]
> Note that one of the pieces that only made sense in Stumptown was the idea of the `<SidebarLeaf>` component and rendering a sidebar not based on `doc.sidebarHTML` but on `doc.related_content`. This I still think is a great idea and would "slot in" nicely if we can figure it out.
> To actually figure it out, we need to break down some sidebar macros and figure out a new routine that can produce and array of arrays rather than a big fat blob of HTML produced by some `FooSidebar.ejs`.
> For example, we can write some Node code that traverses the tree and from it produces something like this:
> 
> ```js
> [
>    {title: "Properties", content: [
>     {title: "forEach", uri: "/en-US/docs/JavaScript/Array/forEach"},
>     {title: "push", uri: "/en-US/docs/JavaScript/Array/push"},
>     ...
>   ]},
>   {title: "Methods", content: [ ... ]},
>   ...
> ]
> ```
> 
> The Yari builder could get ideas based on the front-matter. E.g.
> 
> ```diff
> diff --git a/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html b/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html
> index 0755aac51..7ff8db372 100644
> --- a/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html
> +++ b/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html
> @@ -8,9 +8,8 @@ tags:
>  - Method
>  - Prototype
>  - Reference
> +sidebar: jsref
>  ---
> -<div>{{JSRef}}</div>
> -
>  <p>The <code><strong>forEach()</strong></code> method executes a provided function once
>    for each array element.</p>
>  
> ```
> 
> And what the Yari builder will do is notice the `jsref` identifier in the front-matter and kick of some pure Node JS code (not EJS macros!) that does the figuring out of what the list of lists should be.
> 
> The eventual advantage of all of this is that we can probably make the HTML much slimmer and the sidebar bars will be driven from fresh new pure JS (node) code rather than that cryptic EJS code we have today.

Discussion moved to https://github.com/mdn/yari/discussions/2895

I hope that discussion will suffice to explain why I'm *not* deleting the related-content stumptown left-overs.

**Comment by peterbe** [comment]
@schalkneethling If you want to unblock yourself on https://github.com/mdn/yari/pull/2937 perhaps you can "take over" the review and merge of this PR.

**Review by escattone — APPROVED** [review]
@peterbe Looks and works great!

**Pull request merged**
